---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(data.table)
# plotting
library(ggplot2)
library(colorspace)
library(patchwork)
```

```{r}
data <- fread("data/results/data_strategy_gen.csv")
# rearrange
data$sim_type <- factor(data$sim_type,
  levels = c("foragers", "obligate", "facultative")
)
```

```{r}
# basic plot
# fig_strategy_gen <-
  ggplot(data[sim_type != "foragers" &
    (gen %% 10 == 0 | gen < 100)]) +
  geom_line(aes(gen, value,
    col = variable,
    group = interaction(
      sim_type,
      regrowth,
      replicate,
      variable
    )
  ),
  size = 0.5
  ) +
  facet_grid(sim_type ~ regrowth) +
  scale_color_manual(
    values = qualitative_hcl(3, "Set2", l = 40, rev = T)
  ) +
  theme_custom(grid = T) +
  scale_x_log10() +
  labs(
    y = "proportion of population",
    x = "generations"
  )
```

```{r}
ggsave(fig_strategy_gen,
  filename = "figures/fig_strategy_generations.png",
  dpi = 150
)
```

### Plot for regrowth = 0.1

```{r}
data_0.1 <- data[(gen %% 10 == 0 | gen < 100) & regrowth == 0.1]

# split
data_0.1 <- split(data_0.1, by = "sim_type")

# subfigures
subfig_strategy_gen <- lapply(data_0.1, function(df) {
  ggplot(df) +
    geom_line(aes(gen, value,
      col = variable,
      group = interaction(
        sim_type,
        regrowth,
        replicate,
        variable
      )
    ),
    size = 0.1
    ) +
    geom_point(aes(gen, value,
      col = variable),
      size = 0.2,
      shape = 1)+
    scale_color_manual(
      values = qualitative_hcl(3, "Set2", l = 40, rev = T)
    ) +
    scale_y_continuous(
      labels = scales::percent,
      breaks = seq(0, 0.75, 0.25)
    ) +
    kleptomoveMS::theme_custom(base_size = 8) +
    coord_cartesian(ylim = c(0, 0.75)) +
    scale_x_sqrt(breaks = c(0, 10, 100, 500, 1000)) +
    labs(
      y = "% population", x = NULL
    )
})
```

### Plot fitness

```{r}
data_summary <- data[(regrowth == 0.1) &
  (gen %% 10 == 0 | gen < 100)]
data_summary <- unique(data_summary,
  by = c(
    "sim_type", "replicate",
    "pop_fitness"
  )
)
data_summary <- split(data_summary, by = "sim_type")

subfig_fitness <- lapply(data_summary, function(df) {
  ggplot(df) +
    geom_line(aes(gen, pop_fitness,
      group = interaction(sim_type, replicate)
    ),
    col = "grey20",
    size = 0.1
    ) +
    geom_point(aes(gen, pop_fitness,
      group = interaction(sim_type, replicate)
    ),
    col = "grey20",
    size = 0.2,
    shape = 1
    ) +
    kleptomoveMS::theme_custom(grid = F, base_size = 8) +
    coord_fixed(ylim = c(10, 55), ratio = 0.5) +
    scale_x_sqrt(breaks = c(0, 10, 100, 500, 1000)) +
    labs(
      y = "pop. intake",
      x = "generations"
    )
})
```


```{r}
# make figure
fig_strategy_gen <-
  wrap_plots(
    append(
      subfig_strategy_gen[c("foragers", "obligate", "facultative")],
      subfig_fitness[c("foragers", "obligate", "facultative")]
    )
  ) +
    plot_annotation(
      tag_levels = "a",
      tag_prefix = "(",
      tag_suffix = ")"
    ) &
    theme(plot.tag = element_text(
      face = "bold",
      size = 12
    ))
```

```{r}
ggsave(fig_strategy_gen,
  filename = "figures/fig_02_strategy_generations.png",
  height = 3.5, width = 6
)
```

### Performance of each scenario in handling proportion

```{r}
# get last 10 generations
data_equi <- data[gen > max(gen) - 10, ]

# look at handling and fitness
data_equi <- data[variable == "handling", ]

# boxplot handling time
data_equi_summary <-
  data_equi[, unlist(lapply(.SD, function(x) {
    list(
      median = median(x),
      sd = sd(x)
    )
  }), recursive = F),
  .SDcols = c("pop_fitness"),
  by = c("sim_type", "regrowth")
  ]
# boxplot fitness
fig_strategy_fitness <-
  ggplot(data_equi) +
  geom_line(
    data = data_equi_summary,
    aes(factor(regrowth),
      y = pop_fitness.median,
      col = sim_type,
      group = sim_type
    ),
    lwd = 0.2,
    position = position_dodge(width = 0.25)
  ) +
  geom_pointrange(
    data = data_equi_summary,
    aes(factor(regrowth),
      y = pop_fitness.median,
      ymin = pop_fitness.median -
        pop_fitness.sd,
      ymax = pop_fitness.median +
        pop_fitness.sd,
      fill = sim_type,
      shape = sim_type
    ),
    position = position_dodge(width = 0.25)
  ) +
  scale_fill_manual(
    values = sequential_hcl(3, palette = "Viridis")
      #qualitative_hcl(3, "Cold", l = 70, rev = T)
  ) +
  scale_shape_manual(
    values = c(21, 24, 22)
  ) +
  theme_custom(base_size = 8) +
  # kleptomoveMS::theme_custom()+
  labs(
    x = "regrowth rate",
    y = "total population intake (prey items)"
  )
```

```{r}
ggsave(
  fig_strategy_fitness,
  filename = "figures/fig_03_strategy_fitness.png",
  height = 3, width = 3
)
```

