---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Plotting functional responses

## Plotting replicates separately

```{r}
#### Code for functional response

# load libraries
library(tidyr)
library(stringi)
library(glue)
library(ggplot2)
library(data.table)

# some helper functions
source("code/functional_response.R")
```

Prepare to read data.

```{r}
# simulation type
sim_type <- c("obligate", "facultative", "foragers", "random")

# get the replicates
replicate <- stringr::str_pad(seq_len(3), pad = "0", width = 3)

# growth rates
regrowth <- c(0.001, 0.01, 0.03, 0.05)

# glue data folder names together
data <- crossing(
  sim_type,
  replicate,
  regrowth
)

# get folders
data$folder_path <- glue_data(.x = data,
                              'data/sim_{sim_type}_rep_{replicate}_\\
                                      gro_{regrowth}')
```

Summarise the data and read it in, using the helper functions.

```{r}
# get data
data$data_summary <- lapply(data$folder_path,
                            get_functional_response)

# unnest the data
data <- unnest(data,
               cols = "data_summary")
```

Prepare the data for plotting.

```{r}
# set dt
setDT(data)
data <- split(data, by = c("regrowth", "sim_type"))

# data_reg
data_reg <- data[!stri_detect(names(data), fixed = "0.001")]
```

Make list of plots.

```{r}
fig_fun_response <- 
  lapply(data_reg, function(df) {
    ggplot(df)+
      geom_tile(aes(items, total_agents, 
                    fill = value + 1e-6))+
      facet_grid(replicate~variable)+
      scico::scale_fill_scico(palette = "berlin",
                              direction = -1,
                              limits = c(0, 0.25)
                              # breaks = c(1e-2, 1e0),
                              # labels = c("lower", "higher")
      )+
      # coord_cartesian(xlim = c(0, 2.5),
      #             ylim = c(0, 0.15))+
      # coord_equal()+
      theme_minimal(base_size = 4)+
      theme(legend.position = "top",
            # panel.grid = element_blank(),
            plot.background = element_rect(fill = NA, colour = "grey"),
            legend.key.height = unit(2, units = "mm"),
            axis.title = element_text(face = "bold"),
            legend.title = element_text(face = "bold"))+
      labs(fill = "p.c.in.",
           x = "items",
           y = "agents",
           title = sprintf("sim_type = %s | regrowth = %f",
                           unique(df$sim_type), round(unique(df$regrowth), 2)))
  })
```

```{r}
# wrap and save
fig_fun_response <- patchwork::wrap_plots(fig_fun_response, ncol = 3, nrow = 4)
fig_fun_response
ggsave(fig_fun_response,
       filename = "figures/fig_fun_response.png")
```

## Averaging over replicates

```{r}
# bind data
data <- rbindlist(data)

# average over replicates
data_summary <- data[regrowth > 0.01, list(value = mean(value)),
     by = c("sim_type", "regrowth", "items", "total_agents", "variable")]

# split by sim type
data_summary <- split(data_summary, by = c("sim_type"))
```

```{r}
fig_fun_response <- 
  lapply(data_summary, function(df) {
    ggplot(df)+
      geom_tile(aes(items, total_agents, 
                    fill = value + 1e-6))+
      facet_grid(regrowth~variable)+
      scico::scale_fill_scico(palette = "batlow",
                              direction = -1,
                              limits = c(0, 0.33)
                              # breaks = c(1e-2, 1e0),
                              # labels = c("lower", "higher")
      )+
      coord_cartesian(
        # xlim = c(0, 2.5),
                      ylim = c(0, 0.15))+
      theme_minimal()+
      theme(legend.position = "top",
            # panel.grid = element_blank(),
            plot.background = element_rect(fill = NA, colour = "grey"),
            legend.key.height = unit(2, units = "mm"),
            axis.title = element_text(face = "bold"),
            legend.title = element_text(face = "bold"))+
      labs(fill = "p.c.in.",
           x = "items",
           y = "agents",
           title = sprintf("sim_type = %s",
                           unique(df$sim_type)))
  })
```

```{r}
# wrap and save
fig_fun_response <- patchwork::wrap_plots(fig_fun_response)

ggsave(fig_fun_response,
       filename = "figures/fig_fun_response.png")
```