---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(data.table)
# plotting
library(ggplot2)
library(colorspace)
library(patchwork)
```

```{r}
data <- fread("data_sim/results/data_strategy_gen.csv")
# rearrange
data$sim_type <- factor(data$sim_type,
  levels = c("foragers", "obligate", "facultative", "random")
)

# remove excess growth
data = data[regrowth <= 0.1,]

# remove random
data = data[sim_type != "random",]
```

```{r}
# basic plot
fig_strategy_gen <-
  ggplot(data[sim_type != "foragers" &
    (gen %% 10 == 0 | gen < 100)]) +
  geom_line(aes(gen, value,
    col = variable,
    group = interaction(
      sim_type,
      regrowth,
      replicate,
      variable
    )
  ),
  size = 0.5
  ) +
  facet_grid(sim_type ~ regrowth) +
  scale_color_manual(
    values = qualitative_hcl(3, "Set2", l = 40, rev = T)
  ) +
  kleptomoveMS::theme_custom(grid = F) +
  scale_x_log10() +
  labs(
    y = "proportion of population",
    x = "generations"
  )
```

```{r}
ggsave(fig_strategy_gen,
  filename = "figures/fig_strategy_generations.png",
  dpi = 150
)
```

### Plot for regrowth = 0.01

```{r}
data_0.01 <- data[(gen %% 10 == 0 | gen < 100) & regrowth == 0.01]

# split
data_0.01 <- split(data_0.01, by = "sim_type")

# subfigures
subfig_strategy_gen <- lapply(data_0.01, function(df) {
  ggplot(df) +
    geom_line(aes(gen, value,
      col = variable,
      group = interaction(
        sim_type,
        regrowth,
        replicate,
        variable
      )
    ),
    size = 0.1
    ) +
    geom_point(aes(gen, value,
      col = variable),
      size = 0.2,
      shape = 1)+
    scale_color_manual(
      values = qualitative_hcl(3, "Set2", l = 40, rev = T)
    ) +
    scale_y_continuous(
      labels = scales::percent,
      breaks = seq(0, 0.75, 0.25)
    ) +
    kleptomoveMS::theme_custom(base_size = 8) +
    coord_cartesian(ylim = c(0, 0.75)) +
    scale_x_sqrt(breaks = c(0, 10, 100, 500, 1000)) +
    labs(
      y = "% population", x = NULL
    )
})
```

### Plot fitness

```{r}
data_summary <- data[(regrowth == 0.01) &
  (gen %% 10 == 0 | gen < 100)]
data_summary <- unique(data_summary,
  by = c(
    "sim_type", "replicate",
    "pop_fitness"
  )
)
data_summary <- split(data_summary, by = "sim_type")

subfig_fitness <- lapply(data_summary, function(df) {
  ggplot(df) +
    geom_line(aes(gen, pop_fitness,
      group = interaction(sim_type, replicate)
    ),
    col = "grey20",
    size = 0.1
    ) +
    geom_point(aes(gen, pop_fitness,
      group = interaction(sim_type, replicate)
    ),
    col = "grey20",
    size = 0.2,
    shape = 1
    ) +
    kleptomoveMS::theme_custom(grid = F, base_size = 8) +
    coord_fixed(ylim = c(10, 55), ratio = 0.5) +
    scale_x_sqrt(breaks = c(0, 10, 100, 500, 1000)) +
    labs(
      y = "pop. intake",
      x = "generations"
    )
})
```


```{r}
# make figure
fig_strategy_gen <-
  wrap_plots(
    append(
      subfig_strategy_gen[c("foragers", "obligate",
                            "facultative")],
      subfig_fitness[c("foragers", "obligate", "facultative")]
    )
  ) +
    plot_annotation(
      tag_levels = "a",
      tag_prefix = "(",
      tag_suffix = ")"
    ) &
    theme(plot.tag = element_text(
      face = "bold",
      size = 12
    ))
```

```{r}
ggsave(fig_strategy_gen,
  filename = "figures/fig_strategy_generations.png",
  height = 3.5, width = 6
)
```

### Fitness in relation to regrowth and scenario

```{r}
# get last 10 generations
data_equi <- data[gen > max(gen) - 10 & regrowth <= 0.05, ]

# look at handling and fitness
cols_we_want = setdiff(
  colnames(data_equi),
  c("variable", "value"))
data_fitness <- data_equi[, ..cols_we_want]

# get unique
data_fitness = unique(data_fitness)

# boxplot handling time
data_fitness_summary <-
  data_fitness[, unlist(lapply(.SD, function(x) {
    list(
      median = median(x),
      sd = sd(x)
    )
  }), recursive = F),
  .SDcols = c("pop_fitness"),
  by = c("sim_type", "regrowth")
  ]

# boxplot fitness
fig_strategy_fitness <-
  ggplot() +
  geom_line(
    data = data_fitness_summary,
    aes((regrowth),
      y = pop_fitness.median,
      col = sim_type,
      group = sim_type
    ),
    # lwd = 0.2,
    position = position_dodge(width = 0.005)
  ) +
  geom_errorbar(
    data = data_fitness_summary,
    aes(regrowth,
        ymin = pop_fitness.median -
        pop_fitness.sd,
      ymax = pop_fitness.median +
        pop_fitness.sd,
      group = sim_type),
    lwd = 0.2,
    position = position_dodge(width = 0.005)
  )+
  geom_point(
    data = data_fitness_summary,
    aes((regrowth),
      y = pop_fitness.median,
      fill = sim_type,
      shape = sim_type
    ),
    size = 2,
    position = position_dodge(width = 0.005)
  ) +
  scale_fill_manual(
    values = c("maroon", "dodgerblue", "gold")
  ) +
  scale_colour_manual(
    values = c("maroon", "dodgerblue", "gold")
  ) +
  scale_shape_manual(
    values = c(21, 24, 22)
  ) +
  scale_x_continuous(breaks = c(0.001,
                                0.01,
                                0.025,
                                0.05))+
  kleptomoveMS::theme_custom(base_size = 8) +
  # kleptomoveMS::theme_custom()+
  labs(
    x = "regrowth rate",
    y = "total population intake"
  )
```

```{r}
ggsave(
  fig_strategy_fitness,
  filename = "figures/fig_strategy_fitness.png",
  height = 3, width = 3
)
```

### Foraging and stealing across regrowth and scenario

```{r}
# get the stealing and foraging over regrowth rates
data_strategy_summary = data_equi[variable %in% c("stealing",
                                                  "foraging") &
                                    regrowth <= 0.05, ]

# summarise proportion per sim type and growth rate
data_strategy_summary = 
  data_strategy_summary[, unlist(lapply(.SD, function(x) {
    list(
      median = median(x),
      sd = sd(x)
    )
  }), recursive = F),
  .SDcols = c("value"),
  by = c("sim_type", "regrowth", "variable")]

# split by variable
data_strategy_summary = split(data_strategy_summary,
                              by = "variable")
```

```{r}
# define palette
pal = qualitative_hcl(3, "Set2", l = 70, rev = T)

subfigures_strategy_growth = Map(function(df, name) {
  yaxis_name = sprintf("%% %s", name)
  colour = ifelse(name == "stealing", pal[1], pal[3])
  
  # plot figure
  ggplot(df)+
    geom_path(aes(regrowth, value.median,
                  group = interaction(sim_type, variable)),
                  col = colour)+
    geom_errorbar(
      aes(regrowth,
          ymin = value.median - value.sd,
          ymax = value.median + value.sd),
          lwd = 0.2
    )+
    geom_point(aes(regrowth, value.median,
                        shape = sim_type),
                        fill = colour)+
    scale_shape_manual(
      values = c(21, 24, 22)
    )+
    scale_y_continuous(labels = scales::percent)+
    scale_x_continuous(breaks = c(0.001,  
                                0.05,
                                0.1, 0.25))+
    coord_cartesian(ylim = c(0, 1))+
    kleptomoveMS::theme_custom(base_size = 8)+
    labs(x = "regrowth rate",
         y = yaxis_name)
}, data_strategy_summary, names(data_strategy_summary))

```

## Make Figure 2

```{r}
# prepare plots
line_plots = append(
  subfig_strategy_gen[c("foragers", "obligate",
                          "facultative")],
    subfig_fitness[c("foragers", "obligate", "facultative")]
)

# point plots
point_plots = append(
  subfigures_strategy_growth,
  list(fig_strategy_fitness)
)

# make all into list
all_plots = append(line_plots, point_plots)
```


```{r}
# wrap all figures
figure_2 =
  wrap_plots(all_plots) +
    plot_annotation(
      tag_levels = "a",
      tag_prefix = "(",
      tag_suffix = ")"
    ) &
    theme(plot.tag = element_text(
      face = "bold",
      size = 8
    ))

ggsave(
  figure_2,
  filename = "figures/fig_02_equilibrium.png",
  width = 6, height = 5
)
```

