---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Plotting functional responses

## Plotting replicates separately

```{r}
#### Code for functional response

# load libraries
library(tidyr)
library(stringi)
library(glue)
library(ggplot2)
library(data.table)

# some helper functions
source("code/functional_response.R")
```

Prepare to read data.

```{r}
# simulation type
sim_type <- c("obligate", "facultative", "foragers")

# get the replicates
replicate <- stringr::str_pad(seq_len(3), pad = "0", width = 3)

# growth rates -- read only 0.05
regrowth <- c(0.001, 0.01, 0.03, 0.05,
              0.02, 0.04, 0.075, 0.1, 0.25, 0.005)

# glue data folder names together
data <- crossing(
  sim_type,
  replicate,
  regrowth
)

# get folders
data$folder_path <- glue_data(.x = data,
                              'data/sim_{sim_type}_rep_{replicate}_\\
                                      gro_{regrowth}')
```

Write param combinations.

```{r}
fwrite(data, "data/data_param_combinations.csv")
```


Summarise the data and read it in, using the helper functions.

```{r}
# get data
data$data_summary <- lapply(data$folder_path, function(x) {
  get_functional_response(
    data_folder = x,
    round_value = 0.005,
    drivers = c("items", "total_agents")
  )
})

# unnest the data
data <- unnest(data,
               cols = "data_summary")

# average over replicates and select only the highest growth rate
# data_summary <- data_plot[, 
#                      list(value = mean(value)),
#                      by = c("sim_type", "regrowth",
#                             "items", "total_agents", "variable")]

# remove simulation type foragers and random
# data_summary <- data_summary[sim_type %in% c("facultative", "obligate"), ]

# # make factor
# data$value_cut <- cut(data$value, seq(0, 1, 0.01))

# write file
fwrite(data, file = "data/data_funresp_general.csv")
```

## Functional response: Klepts ~ foragers

```{r}
# get data
data$data_summary <- lapply(data$folder_path, function(x) {
  get_functional_response(
    data_folder = x,
    round_value = 0.001,
    drivers = c("klepts", "foragers")
  )
})

# unnest the data
data_plot <- unnest(data,
               cols = "data_summary")
setDT(data_plot)
```

### Average over replicates

```{r}
# average over replicates and select only the highest growth rate
data_summary <- data_plot[, 
                     list(value = mean(value)),
                     by = c("sim_type", "regrowth",
                            "klepts", "foragers", "variable")]

# remove simulation type foragers and random
# data_summary <- data_summary[sim_type %in% c("facultative", "obligate"), ]

# # make factor
data_summary$value_cut <- cut(data_summary$value, seq(0, 1, 0.01))

# write file
fwrite(data_summary, file = "data/data_funresp_strategy.csv")
```

## Functional response: Foragers ~ items

```{r}
# get data
data$data_summary <- lapply(data$folder_path, function(x) {
  get_functional_response(
    data_folder = x,
    round_value = 0.001,
    drivers = c("items", "foragers")
  )
})

# unnest the data
data_plot <- unnest(data,
               cols = "data_summary")
setDT(data_plot)
```

### Average over replicates

```{r}
# average over replicates and select only the highest growth rate
data_summary <- data_plot[, 
                     list(value = mean(value)),
                     by = c("sim_type", "regrowth",
                            "items", "foragers", "variable")]

# remove simulation type foragers and random
# data_summary <- data_summary[sim_type %in% c("facultative", "obligate"), ]

# # make factor
data_summary$value_cut <- cut(data_summary$value, seq(0, 1, 0.01))

# write file
fwrite(data_summary, file = "data/data_funresp_foragers.csv")
```
