---
editor_options: 
  chunk_output_type: console
---
# Generalised Response: Individual Strategy

```{r}
library(data.table)
library(ggplot2)
library(pals)

# custom functions
source("code/functional_response.R")
```

## Get strategy data

```{r}
# read general fun response and split by sim type
data <- fread("data/data_funresp_strategy.csv")

# subset for max regrowth
data <- data[regrowth == max(regrowth) & 
               sim_type %in% c("facultative", "obligate") ]

# get summary
df <- data[, list(value = mean(value)),
  by = c(
    "sim_type",
    "klepts", "foragers", "variable"
  )
]
```

```{r}
# split by sim type
df <- split(df, by = "sim_type")
```


```{r}
# plot
fig_fun_response_strategy <-
  lapply(df, function(df) {
  ggplot(df)+
  geom_tile(aes(foragers, klepts, 
                fill = value),
            show.legend = T)+
  
  facet_grid(sim_type ~ variable)+
  scale_fill_gradientn(
        colours = (pals::cubehelix(10, r = -2.5)),
        limits = c(1e-6, 0.3),
        breaks = seq(0, 0.3, 0.1),
        na.value = NA
      ) +
  coord_cartesian()+
  theme_bw(base_size = 8, base_family = "sans") +
      theme(
        legend.position = "top",
        # panel.grid = element_blank(),
        legend.key.height = unit(1, units = "mm"),
        legend.background = element_blank()
      ) +
  labs(fill = "per-capita\nintake",
       x = "# foragers",
       y = "# kleptoparasites")
  })

fig_fun_response_strategy <- patchwork::wrap_plots(fig_fun_response_strategy[c(
  # "foragers",
  "obligate",
  "facultative"
  # "random"
)], ncol = 1,
guides = "collect"
) &
  theme(legend.position = "top")

```

```{r}
ggsave(fig_fun_response_strategy,
       filename = "figures/fig_fun_response_strategy.png",
       width = 7, height = 5)
```