---
output: html_document
editor_options: 
  chunk_output_type: console
---
  
# Plot node weight evolution

## Prepare libraries

```{r}
# load libs
library(data.table)
library(ggplot2)
library(patchwork)
library(colorspace)
```

## Load data

```{r}
# read back in
data <- fread("data_sim/results/data_early_0_100_weight_evolution.csv")
# data[, folder_path := stringr::str_replace(folder_path, "data", "data_sim")]

# select growth rates of 0.001, 0.01, 0.1, 0.25
focus_r = c(0.001, 0.01, 0.05)
data = data[regrowth %in% focus_r,]

# handle weight value ranges and use UPPER bound
data[, weight_num := 
       stringi::stri_extract_last(weight_value, 
                                  regex = "[-0-9]+\\.\\d{2}")]
# assign numeric
data[, weight_num := as.numeric(weight_num)]
```

## Prepare summary data

Handler preference

```{r}
# get positive weights for handlers (weight 3)
wt_handler = data[weight_id == 3 & weight_num > 0, ]

# sum proportions
wt_handler = wt_handler[, list(pref_handlers = sum(weight_prop)),
           by = c("sim_type", "replicate", "regrowth", "gen")]
```

```{r}
# plto to check
ggplot(wt_handler)+
  geom_path(aes(gen, pref_handlers,
            group = interaction(sim_type, replicate, regrowth)))
```

Kleptoparasite bias for fixed strategy

```{r}
klept_bias = data[weight_id == 5 & weight_num < 0 & sim_type != "facultative", ]
klept_bias = klept_bias[, list(klept_strategy = sum(weight_prop)),
                        by = c("sim_type", "replicate", "regrowth", "gen")]
```

```{r}
# plot to check
ggplot(klept_bias)+
  geom_path(aes(gen, klept_strategy,
            group = interaction(sim_type, replicate, regrowth)))+
  facet_grid(~sim_type)
```

Handler strategy

```{r}
handler_strategy = data[sim_type == "facultative" & weight_id == 7 & weight_num < 0,]
handler_strategy = handler_strategy[, list(steal_handlers = sum(weight_prop)),
                        by = c("sim_type", "replicate", "regrowth", "gen")]
```

```{r}
ggplot(handler_strategy)+
  geom_path(aes(gen, steal_handlers,
                group = interaction(sim_type, replicate, regrowth)))
```

### Handler preference and klept bias

```{r}
# palette red for strategy/bias and blue for handler 
pal = qualitative_hcl(3, "Set2", l = 40, rev = T)

# labellers
# labels_growth_rate

# labels_sim
```

```{r}
# split by simulation type
data_list = list(wt_handler, klept_bias, handler_strategy)

# melt all
data_list = lapply(data_list, melt, id.vars = c("sim_type", "replicate", "regrowth", "gen"))

# bind list
data_plot = rbindlist(data_list)

# split by scenario
data_plot = split(data_plot, by = "sim_type")
```


```{r}
subplots_fig3 = lapply(data_plot, function(df) {
  ggplot(df)+
  geom_hline(yintercept = 0.5,
             colour = "grey")+
  geom_line(aes(gen, value,
                 col = variable == "pref_handlers",
                 group = interaction(sim_type, replicate, regrowth, variable)))+
  # geom_point(aes(gen, value,
  #                col = variable == "pref_handlers"),
  #            size = 0.1,
  #            shape = 1)+
  scale_colour_discrete_diverging(
    palette = "Blue-Yellow", rev = T
  )+
  scale_x_sqrt(breaks = c(1, 10, 25, 50, 100))+
  scale_y_continuous(labels = scales::percent)+
  coord_equal(ylim = c(0, 1), 
              ratio = 10)+
  facet_grid(~ regrowth,
             labeller = label_both)+
  kleptomoveMS::theme_custom(base_size = 8)+
  theme(title = element_text(size = 8))+
  labs(x = "generation",
         y = "% population")
})

figure_3 =
  wrap_plots(subplots_fig3[c("foragers", "obligate", "random", "facultative")])+
    plot_annotation(
      tag_levels = "a",
      tag_prefix = "(",
      tag_suffix = ")"
    ) &
    theme(plot.tag = element_text(
      face = "bold",
      size = 8
    ))
```

```{r}
# save figure 3
ggsave(
  figure_3,
  filename = "figures/fig_03_preadaptation.png",
  width = 8, height = 4
)
```

