## Foragers and items

```{r}
# read general fun response and split by sim type
data <- fread("data/data_funresp_foragers.csv")

# round over more items
data[, items_round := floor_any(items, 0.01)]

# get summary
df <- data[, list(value = mean(value)),
            by = c("sim_type", 
                   "items_round", "foragers", "variable")]
```


```{r}
fig_fun_response <-
  ggplot(df)+
  geom_tile(aes(items_round, foragers,
                fill = value),
            show.legend = T)+
  # geom_abline(slope = 1, lwd = 0.2)+
  facet_grid(sim_type ~ variable)+
  scale_fill_gradientn(colours = (pals::cubehelix(10,
                                                  r = -2.5)),
                       limits = c(0, 0.3),
                       breaks = seq(0, 0.3, 0.1))+
  coord_fixed(
    ratio = 30
  )+
  theme_bw(
    base_size = 8
  )+
  theme(legend.position = c(0.95, 0.75),
        # panel.grid = element_blank(),
        legend.key.width = unit(1, units = "mm"),
        legend.background = element_blank())+
  labs(fill = "p.c.in.",
       x = "# food items",
       y = "# foragers",
       title = "functional response: intake rate ~ items + foragers")
# })
fig_fun_response
```

```{r}
# wrap and save
ggsave(fig_fun_response,
       filename = "figures/fig_fun_response_foragers.png",
       width = 7, height = 5)
```



## Intake ~ kleptoparasites controlling for foragers

```{r}
# get forager levels
forager_levels <- c(0.005, 0.01, 0.02, 0.04)

# round foragers
data[, `:=`(forager_round = floor_any(foragers, 0.01),
            klepts_round = floor_any(klepts, 0.005))]

# gather data, first select items
df_summary <- data[forager_round %in% c(forager_levels) &
                   variable != "pc_intake_total",]

df_summary <- df_summary[, list(value = mean(value),
                                sd_value = sd(value)),
           by = c("sim_type", "variable", "forager_round", "klepts_round")]

# make scatterplot
fig_fun_response_agents <-
  ggplot(df_summary)+
  geom_point(aes(klepts_round, value, 
                 colour = variable),
             alpha = 1, size = 1, shape = 1, stroke = 1,
             position = position_dodge(width = 0.002))+
  geom_errorbar(aes(klepts_round, 
                    ymin = value - sd_value,
                    ymax = value + sd_value,
                    colour = variable),
                width = 0.002,
                position = position_dodge(width = 0.002))+
  scale_colour_manual(values = pals::coolwarm(2),
                      labels = c("foragers", "klepts", "total"))+
  facet_grid(sim_type ~ forager_round, scales = "free",
             labeller = label_both, drop = T)+
  theme_grey(base_size = 6, base_family = "sans")+
  theme(legend.position = "top",
        legend.key.height = unit(1, units = "mm"),
        legend.background = element_blank())+
  labs(fill = "p.c.in.",
       x = "# kleptoparasites",
       y = "per-capita intake",
       colour = "strategy",
       title = "functional response: intake rate ~ kleptoparasites + foragers")

fig_fun_response_agents
```

```{r}
ggsave(fig_fun_response_agents,
       filename = "figures/fig_fun_response_strategy_agents.png",
       width = 6, height = 4)
```