---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Plotting functional responses

## Plotting replicates separately

```{r}
#### Code for functional response

# load libraries
library(tidyr)
library(stringi)
library(glue)
library(ggplot2)
library(data.table)
```

Prepare to read data.

```{r}
# simulation type
sim_type <- c("obligate", "facultative", "foragers")

# get the replicates
replicate <- stringr::str_pad(seq_len(3), pad = "0", width = 3)

# growth rates -- read only 0.05
regrowth <- c(0.001, 0.01, 0.03, 0.05)

# glue data folder names together
data <- crossing(
  sim_type,
  replicate,
  regrowth
)

# get folders
data$folder_path <- glue_data(.x = data,
                              'data_sim/sim_{sim_type}_rep_{replicate}_\\
                                      gro_{regrowth}')
```

Write param combinations.

```{r}
fwrite(data, "data/data_param_combinations.csv")
```

## Function response: PC Intake ~ all agents

Summarise the data and read it in, using the helper functions.

```{r}
# get data
data$data_summary <- lapply(data$folder_path, function(x) {
  kleptomoveMS::get_functional_response(
    data_folder = x,
    n_time = 200,
    round_value = 0.005,
    drivers = c("total_agents")
  )
})

# unnest the data
data_summary <- unnest(data,
               cols = "data_summary")
# write file
fwrite(data_summary, file = "data/results/data_funresp_agents.csv")
```

## Functional response: PC Intake ~ klepts and foragers

```{r}
# remove old
data$data_summary <- NULL
gc()

# get new data
data$data_summary <- lapply(data$folder_path, function(x) {
  get_functional_response(
    data_folder = x,
    n_time = 200,
    round_value = 0.005,
    drivers = c("klepts", "foragers")
  )
})

# unnest the data
data_summary <- unnest(data,
               cols = "data_summary")

# write to file
fwrite(data_summary, file = "data/results/data_funresp_strategy.csv")
```

## Functional response: PC Intake ~ items

```{r}
# remove old
data$data_summary <- NULL
gc()

# get new data
data$data_summary <- lapply(data$folder_path, function(x) {
  get_functional_response(
    data_folder = x,
    n_time = 200,
    round_value = 0.005,
    drivers = c("items")
  )
})

# unnest the data
data_summary <- unnest(data,
               cols = "data_summary")

# write to file
fwrite(data_summary, file = "data/results/data_funresp_intake_items.csv")
```

## Functional response: All agents, klepts, foragers ~ items

```{r}
# remove old
data$data_summary <- NULL
gc()

# get data
data$data_summary <- lapply(data$folder_path, function(x) {
  get_functional_response(
    data_folder = x,
    round_value = 0.005,
    n_time = 200,
    response = c("total_agents", "klepts", "foragers"),
    drivers = c("items", "foragers_intake", "klepts_intake")
  )
})

# unnest the data
data_summary <- unnest(data,
               cols = "data_summary")

# write 
fwrite(data_summary, file = "data/results/data_funresp_predators_items_intake.csv")
```

```{r}
setDT(data_summary)
data_summary_2 = data_summary[, list(meanv = mean(value),
                                   medv = median(value),
                                   sdv = sd(value)),
                              by = c("sim_type",
                                     "regrowth", "items",
                                     "foragers_intake", "klepts_intake",
                                     "variable")]
# write 
fwrite(data_summary_2, file = "data/results/data_funresp_predators_items_intake_2.csv")
```

```{r}
# convert itmes
data_summary_2[, c("items", "foragers_intake",
                   "klepts_intake") := lapply(.SD, get_lower),
               .SDcols = c("items", "foragers_intake", "klepts_intake")]
```

```{r}
data_summary_3 = copy(data_summary_2)
data_summary_3[, total_food := items + foragers_intake]
data_summary_3[, total_food := round(total_food, 2)]
```
```{r}
data_summary_3 = data_summary_3[, list(meanv = mean(meanv),
                                   medv = median(meanv),
                                   sdv = sd(meanv)),
                              by = c("sim_type",
                                     "regrowth", "total_food",
                                     "variable")]
```

```{r}
ggplot(data_summary_3[variable != "total_agents"])+
  geom_point(aes(total_food, meanv,
                 col = variable),
             size = 0.1)+
  facet_grid(sim_type ~ regrowth)+
  coord_cartesian(ylim = c(0, 0.5))+
  scale_colour_brewer(palette = "Set1")
```

