
# Plot node weight evolution

```{r}
# load libs
library(data.table)
library(ggplot2)

# get helper functions
source("code/helper_functions.R")
```

```{r}
# read parameter combinations
param_combinations <- fread("data/results/data_param_combinations.csv")

# get weight evolution every 10 generation
# from each simulation
temp_gen_data <- lapply(param_combinations$folder_path, 
                        function(x) {
                          get_sim_weight_evol(data_folder = x,
                                              generations = seq(1, 999, 25))
                        }
)
```

```{r}
# bind with parameters
data <- param_combinations
data[, wt_data := temp_gen_data]

# unnest
data <- data[, unlist(wt_data, recursive = F),
             by = list(sim_type, replicate, regrowth)]
fwrite(data, file = "data/results/data_weight_evolution.csv")
```

```{r}
# read back in
data <- fread("data/results/data_weight_evolution.csv")

# handle weight value ranges and use UPPER bound
data[, weight_num := 
       stringi::stri_extract_last(weight_value, 
                             regex = "[-0-9]+\\.\\d{2}")]

# make character
data[, weight_num := as.numeric(weight_num)]
```

```{r}
# check single plot
ggplot(data = data[regrowth == 0.05 & 
                     sim_type == "facultative" &
                     replicate == 1, ])+
  geom_tile(aes(gen, 
                reorder(weight_num, as.numeric(weight_num)), 
                fill = weight_prop))+
  scale_y_discrete(breaks = c(-1.01, 0.04, 0.97),
                   labels = c("-1", "0", "+1"))+
  facet_grid(~weight_id)
```


## Prepare plots

```{r}
# get label weights
label_wt <- c(
  # sprintf("weight: %s", c(2:8, 99))
  c("m(non-h)", "m(hand)", "m(food)",
    "f(bias)", "f(non-h)", "f(hand)", "f(food)", "f(total)")
)
names(label_wt) <- c(seq(2, 8), 99)

# split the data
data2 <- split(data, by = c("sim_type"))

# plot the timeline
plots <- Map(function(le) {
  
  # split by regrowth
  le <- split(le, by = "regrowth")
  
  subfigures <- lapply(le, function(df) {
    # get plot title
    title <- sprintf("scenario: %s\nregrowth: %.*f",
                     unique(df$sim_type),
                     3,
                     unique(df$regrowth)) 
    
    # get plot
    ggplot(df)+
      geom_tile(aes(gen, 
                    reorder(weight_num, as.numeric(weight_num)), 
                    fill = weight_prop),
                show.legend = FALSE)+
      geom_hline(yintercept = 25,
                 lwd = 0.1, col = "grey")+
      facet_grid(weight_id ~ replicate, 
                 labeller = labeller(weight_id = label_wt,
                                     replicate = label_both))+
      scale_y_discrete(breaks = c(-1.01, 0.04, 0.97),
                       labels = c("-1", "0", "+1"))+
      scale_fill_gradientn(colours = rev(pals::kovesi.linear_bmy_10_95_c78(10)),
                           limits = c(1e-2, 1),
                           na.value = NA)+
      theme_bw(base_size = 8)+
      theme(axis.text.x = element_blank(),
            panel.grid = element_blank())+
      labs(x = "generation", y = "value",
           title = title)
  })
  
  figure <- patchwork::wrap_plots(subfigures, ncol = 10)
  
  # figure filename
  fig_name <- unique(le[[1]]$sim_type)
  filename = sprintf("figures/fig_node_weight_%s.png",
                     fig_name)
  message(fig_name)
  ggsave(figure,
         filename = filename,
         height = 11,
         width = 20,
         units = "in")
  
  return(figure)
  
}, data2)


```

