---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(data.table)
library(dplyr)
library(stringr)
library(ggplot2)
library(colorspace)
library(patchwork)
```

Prepare the data for plotting.

```{r}
data <- fread("data/results/data_agent_distribution.csv")
max_capacity = 5
```


```{r}
# relevel the layer names for better plotting
data$layer <- forcats::fct_relevel(
  data$layer,
  c(
    "klepts", "foragers", "items",
    "klepts_intake", "foragers_intake",
    "pc_intake_klepts",
    "pc_intake_forager"
  )
)
# relevel the simulation (strategy) type
data$sim_type <- forcats::fct_relevel(
  data$sim_type,
  "foragers", "obligate", "facultative", "random"
)

# regroup data
data$layer_type <- dplyr::case_when(
  stringi::stri_detect(data$layer, fixed = "pc_intake") ~ "per_capita_intake",
  stringi::stri_detect(data$layer, fixed = "item") ~ "items",
  stringi::stri_detect(data$layer, fixed = "intake") ~ "intake",
  TRUE ~ "strategy count"
)
```

More plotting preparation.

```{r}
# remove random
data <- data[regrowth %in% c(0.001, 0.01, 0.05, 0.1, 0.25), ]

# remove intake etc
data = data[!layer_type %in% c("intake", "per_capita_intake"), ]

data[, qual := cap * regrowth / (max_capacity ^ 2)]

# split the data by growth rate
data_plot <- split(data, by = c("sim_type", "layer_type"))
data_plot <- data_plot[sapply(data_plot, function(x) {
  nrow(x) > 1
})]

# arrange order
library(stringr)
data_plot <- data_plot[c(
  str_which(names(data_plot), "forager"),
  str_which(names(data_plot), "obligate"),
  str_which(names(data_plot), "facul"),
  str_which(names(data_plot), "random")
)]
```

```{r}
# prepare palette
pal = values = qualitative_hcl(3, "Set2", l = 40, rev = T)
```


```{r}
subplots <-
  Map(
    function(df) {
      if (!unique(df$layer)[[1]] == "items") {
        pal <- c(
          pal[3], pal[1]
        )
        shapes = c(1)
      } else {
        pal <- pal[2]
        shapes = 0
      }
      
      # limits
      if (df$layer_type == "strategy count") {
        y_lim = c(0, 0.15)
        y_axis = "# individuals"
      } else if (df$layer_type == "per_capita_intake") {
        y_lim = c(0, 0.15)
        y_axis = "intake rate"
      } else {
        y_lim = c(0, 5)
        y_axis = "# prey items"
      }
      

      ggplot(df) +
        geom_line(aes(qual, mean_val,
          col = interaction(regrowth, layer),
          group = interaction(regrowth, replicate, gen, layer)
        ),
        show.legend = F
        ) +
        # geom_point(aes(cap, mean_val,
        #   col = interaction(regrowth, layer),
        #   group = interaction(regrowth, replicate, gen),
        #   shape = layer
        # ),
        # show.legend = F,
        # alpha = 0.5
        # ) +
        scale_shape_manual(
          values = rep(shapes, each = length(unique(df$regrowth)))
        )+
        scale_colour_manual(
          values = rep(pal, each = length(unique(df$regrowth)))
        ) +
        # facet_grid(~regrowth)+
        kleptomoveMS::theme_custom(base_size = 8
                                   )+
        theme(title = element_text(size=6))+
        coord_cartesian(
          ylim = y_lim,
          xlim = c(0, 0.05),
          expand = T
        ) +
        labs(
          x = "cell r (cap * regrowth / K)",
          y = y_axis,
          title = unique(df$sim_type)
        )
    },
    data_plot
  )
```

```{r}
figure_05 <-
  wrap_plots(subplots, ncol = 2) +
  plot_annotation(
    tag_levels = "a",
    tag_prefix = "(",
    tag_suffix = ")"
  ) &
  theme(plot.tag = element_text(
    face = "bold",
    size = 8
  ))

ggsave(figure_05,
  filename = "figures/fig_05_agent_distribution.png",
  width = 3, height = 6
)
```
