---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Landscape effects

```{r}
# to handle data and plot
library(data.table)
library(glue)
library(ggplot2)
library(colorspace)
library(patchwork)
```

## Read p clueless

```{r}
# focus r
focus_r = c(0.01)

# read clueless data
data = fread("data_sim/results/data_p_clueless.csv")
data[, path :=  NULL]
data = data[regrowth %in% focus_r,]
data[, sim_type := ifelse(sim_type == "forager", "foragers", sim_type)]

# remove v1
data[, V1 := NULL]

# remove random
data = data[sim_type != "random"]
```

## Read weight evol

```{r}
data_wt = fread("data_sim/results/data_early_0_100_weight_evolution.csv")

# select growth rates of 0.001, 0.01, 0.1, 0.25
data_wt = data_wt[regrowth %in% focus_r,]

# handle weight value ranges and use UPPER bound
data_wt[, weight_num := 
       stringi::stri_extract_last(weight_value, 
                                  regex = "[-0-9]+\\.\\d{2}")]
# assign numeric
data_wt[, weight_num := as.numeric(weight_num)]

# remove random
data_wt = data_wt[sim_type != "random"]

# reorder data factors
data_wt$sim_type = factor(data_wt$sim_type,
                          levels = c("foragers", "obligate", "facultative"))
```

### Klept bias

```{r}
klept_bias = data_wt[weight_id == 5 & weight_num < 0 & sim_type != "facultative", ]
klept_bias = klept_bias[, list(klept_strategy = sum(weight_prop)),
                        by = c("sim_type", "replicate", "regrowth", "gen")]
```

### Handler strategy

```{r}
handler_strategy = data_wt[sim_type == "facultative" & weight_id == 7 & weight_num < 0,]
handler_strategy = handler_strategy[, list(klept_strategy = sum(weight_prop)),
                        by = c("sim_type", "replicate", "regrowth", "gen")]
```

### Merge weight strategy

```{r}
data_wt = rbindlist(list(klept_bias, handler_strategy))
```


## Read proportion strategy data

```{r}
# get data
data_strat = fread("data_sim/results/data_strategy_gen.csv")
data_strat= data_strat[sim_type != "random"]

# subset for klept prop
data_strat = data_strat[variable == "stealing" &
                          regrowth %in% focus_r, ]

# dcast
data_strat = dcast(data_strat, sim_type + replicate + 
                     regrowth + gen + pop_fitness + conflicts ~ variable,
                   value.var = "value")

# join with land data
data_strat = merge(data_strat, data, 
                   by = c("gen", "replicate", "regrowth", "sim_type"),
                   all.y = TRUE)

# join with data_wt
data_strat = merge(data_strat, data_wt)

# melt
data = copy(data_strat)

data = melt(data, 
            id.vars = c("gen", "replicate", 
                        "regrowth", "sim_type"))

# set factor order
data$sim_type = factor(data$sim_type,
                          levels = c("foragers", "obligate", "facultative"))

# remove variables
data = data[variable %in% 
              c("stealing", "p_clueless", "klept_strategy"), ]

# set factor
data$variable = factor(data$variable,
                       levels = c("p_clueless", "klept_strategy", "stealing"))

# split data
data = split(data, by = "sim_type")
```


```{r}
# fix palettes to be same as previously used
this_red = colorspace::qualitative_hcl(3, "Set2", l = 40, rev = T)[3]
this_yellow = colorspace::diverging_hcl(3, palette = "Blue-Yellow")[3]

# make subplots
subplots = lapply(data, function(df) {
  
ggplot(df)+
  geom_path(aes(gen, value,
                col = variable,
                group = interaction(replicate, variable)))+
  geom_vline(
    xintercept = c(10, 40),
    size = 0.2,
    lty = 2,
  )+
  scale_colour_manual(
    values = c(
      "p_clueless" = "black",
      "stealing" = this_red,
      "klept_strategy" = this_yellow
    )
  )+
  scale_y_continuous(
    labels = scales::percent
  )+
  coord_cartesian(xlim = c(0, 75),
                  ylim = c(0, 1))+
  kleptomoveMS::theme_custom()+
  theme(
    # legend.position = "top"
  )+
  labs(
    x = "Generation",
    y = NULL
  )
})

# work on adding lines at different levels

```

## Show landscape for each sim type

Here we show a landscape with and without clues at 1, 10, and 40th generation for $r_{max}$ = 0.01.

### Items landscape

```{r}
# list folders
paths = list.dirs("data_sim/for_landscape/", recursive = F)

# select gens
gens_for_figure = stringr::str_pad(c(10, 40),width = 5, pad = "0")

# get paths for files
landscape_data = CJ(gen = gens_for_figure,
                    path = paths)

# add sim_type
landscape_data[, sim_type := rep(c("facultative", "foragers", "obligate"), 2)]

# get paths
landscape_data$image = glue_data(landscape_data, "{path}/{gen}.png")

# get data
landscape_data$data = lapply(landscape_data$image, 
                             kleptomoveMS::read_landscape,
                             layer = 4,
                             crop_dim = 25,
                             type = "items")

# convert gen to numeric
landscape_data[, gen := as.numeric(gen)]

# unlst
landscape_items = landscape_data[, unlist(data, recursive = F), 
                                by = c("sim_type", "gen")]
```

### Gradient landscape


```{r}
# get data
landscape_data$data = lapply(landscape_data$image, 
                             kleptomoveMS::read_landscape,
                             layer = 4,
                             crop_dim = 25,
                             type = "gradient")
# unlst
landscape_gradient = landscape_data[, unlist(data, recursive = F), 
                                by = c("sim_type", "gen")]
```

### Merge landscapes

```{r}
# landscape overall
landscape = merge(landscape_items, landscape_gradient)

# melt
landscape = melt(landscape, id.vars = c("sim_type", "gen", "x", "y"))

# split by sim_type
landscape = split(landscape, by = c("sim_type", "variable"))
```


### Plot landscape

```{r}
subplot_land = lapply(landscape, function(df) {
  
  pal = sequential_hcl(5, palette = "Terrain", rev = T)[4]
  # set palette
  if (unique(df$variable) == "items") {
    pal = sequential_hcl(5, palette = "Terrain", rev = T)
  }
  
  ggplot(df)+
    geom_tile(aes(x, y, fill = (value)),
              show.legend = F)+
    facet_grid(~ gen, labeller = label_both)+
    scale_fill_gradientn(
      colours = pal,
      na.value = ifelse(unique(df$variable) == "items", "white", "grey20"),
      limits = c(0.7, NA)
    )+
    coord_cartesian(expand = F)+
    theme_custom()+
    theme(axis.text = element_blank(),
          axis.title = element_blank())
})

# arrange order
sim_types = c("foragers", "obligate", "facultative")

# figure names
fignames = c(glue('{sim_types}.items'), glue('{sim_types}.gradient'))
# arrange plots in order
subplot_land = subplot_land[fignames]
```


## Figure 6

```{r}
# make figure 6
figure_6 =
wrap_plots(append(subplots[c("foragers", 
                      "obligate", "facultative")],
                  subplot_land))+
    plot_annotation(
      tag_levels = "a",
      tag_prefix = "(",
      tag_suffix = ")"
    ) &
    theme(plot.tag = element_text(
      face = "bold",
      size = 8
    ))

ggsave(
  figure_6,
  height = 5,
  width = 9,
  filename = "figures/fig_06_landscape_effect.png"
)
```

