---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Behavioural syndrome

```{r}
# to handle data and plot
library(data.table)
library(glue)

library(ggplot2)
library(colorspace)
library(patchwork)
```

## show node weight

```{r}
# get raw data
data_nodes = fread("data_sim/results/data_early_0_100_weight_evolution.csv")
# subset
data_nodes = data_nodes[sim_type == "obligate" &
                          regrowth == 0.01 &
                          weight_id %in% c(3, 5),]
# get numeric lower bounds
data_nodes[, weight_num := as.numeric(
  stringi::stri_extract_last(weight_value,
    regex = "[-0-9]+\\.\\d{2}"
  )
)]
```

```{r}
fig7a =
  ggplot(data_nodes[weight_prop > 0.001 &
                  weight_id == 5,])+
  geom_tile(
    aes(x = gen, 
        y = factor(weight_num),
        fill = weight_prop)
  )+
  geom_hline(
    yintercept = 0,
    col = "grey20",
    lty = 3,
    size = 0.3
  )+
  scale_fill_continuous_sequential(
    palette = "Heat2"
  )+
  scale_y_discrete(
    breaks = c(-0.97, 1.01),
    labels = c("Kleptoparasite", "Forager")
  )+
  coord_cartesian(expand = F)+
  theme_classic(base_size = 8)+
  theme(
    legend.position = "top",
    strip.background = element_blank(),
    strip.text = element_text(face = "italic", hjust = 0),
    axis.text.y = element_text(angle = 90, hjust = 0.5),
    legend.key.height = unit(1, units = "mm")
  )+
  facet_grid(~ replicate, labeller = label_both)+
  labs(x = "Generation", y = "Behavioural strategy",
       fill = "Prop. indivs.")
```

## Prepare strategy-wise weight data WIP

```{r}
data_strategy_weight = copy(data_nodes)
data_strategy_weight = data_strategy_weight[!(weight_id == 5 & !weight_num %in% c(-0.97, 1.01)), ]
data_strategy_weight = data_strategy_weight[, 
                          weight_prop := weight_prop / sum(weight_prop),
                          by = c("sim_type", "replicate", "regrowth")]
```


```{r}
# fig7b = 
  ggplot(data_nodes[weight_prop > 0.001 &
                  weight_id == 3,])+
  geom_tile(
    aes(x = gen, y = weight_num,
        fill = weight_prop)
  )+
  geom_hline(
    yintercept = 0,
    col = "grey20",
    lty = 3,
    size = 0.3
  )+
  scale_fill_distiller(
    palette = "Oranges",
    direction = 1,
    labels = scales::percent
  )+
  scale_y_continuous(
    breaks = c(-0.5, 0.5),
    labels = c("Avoidance", "Preference")
  )+
  coord_cartesian(expand = F)+
  kleptomoveMS::theme_custom(base_size = 8)+
  theme(
    legend.key.height = unit(1, units = "mm")
  )+
  facet_grid(~ replicate, labeller = label_both)+
  labs(x = "Generation", y = "Weight handler response",
       fill = "Prop. indivs.")
```

```{r}
# get data
data <- fread("data_sim/results/data_syndrome.csv")

# recode variables
data[, c("klept_bias", "handler_pref",
         "item_pref", "nh_pref") := list(
  factor(ifelse(klept_bias, "forager", "klept")),
  factor(ifelse(handler_pref, "prefers handlers", "avoids handlers"),
    levels = c("prefers handlers", "avoids handlers")
  ),
  factor(ifelse(item_pref, "prefers items", "avoids items")),
  factor(ifelse(nh_pref, "prefers nh", "avoids nh"))
)]
```

```{r}
# counter by klept and handler
data = data[, list(N = sum(N)), 
     by = c("sim_type", "replicate", "regrowth", "klept_bias", "handler_pref", "gen")]

# get proportion
data[, prop_per_strat := N / sum(N), 
     by = c("gen", "klept_bias", "regrowth", "replicate")]

# # count handler pref per strategy as total
# who drives the rise in handlers
# data_hp_total = copy(data)[handler_pref == "prefers handlers",]
# data_hp_total[, total_handlers := sum(N),
#               by = c("gen", "regrowth", "replicate")]
# data_hp_total[, prop_total := N / total_handlers]
```

```{r}
fig7c =
ggplot(data[regrowth == 0.01, ]) +
  geom_path(
    aes(
      x = gen,
      y = prop_per_strat,
      col = interaction(klept_bias, handler_pref),
      # size = handler_pref,
      group = interaction(sim_type, klept_bias, handler_pref, replicate)
    )
  ) +
  scale_colour_manual(
    values = c(
      "forager.prefers handlers" = "royalblue",
      "forager.avoids handlers" = "lightblue",
      "klept.prefers handlers" = "darkred",
      "klept.avoids handlers" = "indianred"
    ),
    name = NULL,
    labels = c(
      "forager.prefers handlers" = "Forager, prefers handlers",
      "forager.avoids handlers" = "Forager, avoids handlers",
      "klept.prefers handlers" = "Klept., prefers handlers",
      "klept.avoids handlers" = "Klept., avoids handlers"
    )
  ) +
  coord_cartesian(
    ylim = c(0, 1),
    xlim = c(1, 50)
  ) +
  labs(
    x = "Generation",
    y = "Prop. handler response"
  ) +
  # scale_x_log10()+
  kleptomoveMS::theme_custom(grid = F, base_size = 8) +
  theme(legend.position = "top",
        legend.key.height = unit(1, units = "mm"))+
  guides(colour = guide_legend(nrow = 2, byrow = TRUE))
```

```{r}
fig_7 =
  wrap_plots(
    fig7a, fig7b, fig7c,
    design = "AB\nC#"
  )+
  plot_annotation(
    tag_levels = "A"
  ) &
  theme(
    plot.tag = element_text(
      face = "bold",
      size = 12
    ),
    legend.position = "top"
  )
```


```{r}
ggsave(fig_7,
       filename = "figures/fig_07.png",
       width = 125,
       height = 125, units = "mm")
```

