---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(data.table)
library(kleptomoveMS)
# plotting
library(ggplot2)
```

## Agents ~ items

```{r}
# read data
data <- fread("data_sim/results/data_layer_counts_1_150.csv")

# get potential intake
data[, potential_in := get_potential_intake(0.2, items)]

# get correlation
data_summary <- data[, list(
  cf = cor.test(agents, potential_in)[["estimate"]],
  cfp = cor.test(agents, potential_in)[["p.value"]]
),
by = c("sim_type", "gen", "replicate", "regrowth")
]

# # get summary
data_summary_cf <- data_summary[cfp <= 0.05, list(
  mean_c = mean(cf, na.rm = TRUE),
  median_c = median(cf, na.rm = TRUE),
  sd_c = sd(cf, na.rm = TRUE)
), by = c("sim_type", "gen", "regrowth")]

# convert median to running median
data_summary_cf[, `:=`(
  runmed_cf = runmed(median_c, k = 7),
  rollmean_cf = frollmean(mean_c, n = 3)
),
by = c("sim_type", "regrowth")
]

# write data
fwrite(data_summary, file = "data_sim/results/data_matching_rule.csv")
fwrite(data_summary_cf, file = "data_sim/results/data_matching_rule_smooth.csv")
```

## Agents ~ quality

```{r}
# read data
data <- fread("data_sim/results/data_quality_counts_1_150.csv")

# get correlation
data_summary <- data[, list(
  cf = cor.test(agents, quality)[["estimate"]],
  cfp = cor.test(agents, quality)[["p.value"]]
),
by = c("sim_type", "gen", "replicate", "regrowth")
]

# # get summary
data_summary_cf <- data_summary[cfp <= 0.05, list(
  mean_c = mean(cf, na.rm = TRUE),
  median_c = median(cf, na.rm = TRUE),
  sd_c = sd(cf, na.rm = TRUE)
), by = c("sim_type", "gen", "regrowth")]

# convert median to running median
data_summary_cf[, `:=`(
  runmed_cf = runmed(median_c, k = 7),
  rollmean_cf = frollmean(mean_c, n = 3)
),
by = c("sim_type", "regrowth")
]

# write data
fwrite(data_summary, file = "data_sim/results/data_quality_matching_rule.csv")
fwrite(data_summary_cf, file = "data_sim/results/data_quality_matching_rule_smooth.csv")
```


```{r}
# exploratory plot
ggplot() +
  geom_hline(
    yintercept = 0,
    # size = 0.1,
    col = "red"
  ) +
  # geom_point(
  #   data = data_summary,
  #   aes(
  #     x = gen,
  #     y = cf,
  #     col = sim_type
  #   )
  # )+
  geom_path(
    data = data_summary_cf,
    aes(
      x = gen,
      y = median_c,
      # ymin = mean_c - sd_c,
      # ymax = mean_c + sd_c,
      col = sim_type
    )
  ) +
  scale_colour_manual(
    values = c(
      foragers = "maroon",
      obligate = "dodgerblue",
      facultative = "darkorange",
      random = "grey"
    ),
    labels = c(
      foragers = "Foragers",
      obligate = "Fixed",
      facultative = "Conditional",
      random = "Random"
    )
  ) +
  kleptomoveMS::theme_custom(grid = TRUE) +
  theme(legend.position = "top") +
  facet_grid(~regrowth, labeller = label_both) +
  labs(x = "generations", y = "correlation agents ~ potential intake rate")
```

```{r}
ggsave(
  filename = "figures/fig_matching_rule.png"
)
```

