---
output: html_document
editor_options: 
  chunk_output_type: console
---
  
# Plot node weight evolution
  
```{r}
# load libs
library(data.table)
library(ggplot2)
library(patchwork)
library(colorspace)
```

```{r}
# read back in
data <- fread("data/results/data_weight_evolution.csv")

# handle weight value ranges and use UPPER bound
data[, weight_num := 
       stringi::stri_extract_last(weight_value, 
                                  regex = "[-0-9]+\\.\\d{2}")]
# assign numeric
data[, weight_num := as.numeric(weight_num)]
```

```{r}
test <- data[regrowth == 0.05 & 
               sim_type == "facultative"]

test <- test[weight_prop > 0.001, 
             list(n_pos = as.double(sum(weight_num > 0)),
                  n_neg = as.double(sum(weight_num < 0)),
                  p_neg = sum(weight_prop[weight_num < 0]),
                  p_pos = sum(weight_prop[weight_num > 0])),
             by = c("sim_type", "replicate", 
                    "regrowth", "weight_id", "gen")]

test <- na.omit(test)

test[, p_pos_var := n_pos / (n_pos + n_neg)]
test[, n_morphs := n_pos + n_neg]

ggplot(test, 
       aes(group = replicate))+
  geom_ribbon(
    aes(x = gen, 
        ymin = 1 - p_neg,
        ymax = (1 - p_neg) + (n_pos/50)),
    fill = "royalblue",
    alpha = 0.3
  )+
  geom_ribbon(
    aes(x = gen, 
        ymin = 1 - p_neg,
        ymax = (1 - p_neg) - (n_neg/50)),
    fill = "red",
    alpha = 0.3
  )+
  geom_line(aes(gen, 1 - p_neg),
            lwd = 0.2)+
  facet_grid(~ weight_id)+
  # scale_fill_viridis_c(option = "B")+
  scale_colour_gradientn(
    colours = c(pals::kovesi.diverging_bkr_55_10_c35(3)),
    # limits = c(-10, 10),
    na.value = "grey90"
  )+
  # scale_y_continuous(breaks = c(-1, 0, 1),
  #                    labels = c("-tive", "0", "+tive"))+
  ggthemes::theme_few(base_family = "sans")+
  labs(x = "generation",
       y = "p(+ve weight)",
       fill = "diversity")

  ggsave(filename = "test.png")
```


## Prepare plots

```{r}
# get label weights
label_wt <- c(
  # sprintf("weight: %s", c(2:8, 99))
  c("m(non-h)", "m(hand)", "m(food)",
    "f(bias)", "f(non-h)", "f(hand)", "f(food)", 
    "m(indivs)",
    "f(total)")
)
names(label_wt) <- c(seq(2, 8), 51, 99)

# subset
data <- data[regrowth %in% c(0.001, 0.01, 0.05, 0.1, 0.25)]

# split the data
data2 <- split(data, by = c("sim_type"))

# plot the timeline
plots <- Map(function(le) {
  
  # split by regrowth
  le <- split(le, by = "regrowth")
  
  subfigures <- lapply(le, function(df) {
    # get plot title
    title <- sprintf("scenario: %s\nregrowth: %.*f",
                     unique(df$sim_type),
                     3,
                     unique(df$regrowth)) 
    
    
    df <- df[weight_prop > 0.001, 
             list(n_pos = as.double(sum(weight_num > 0)),
                  n_neg = as.double(sum(weight_num < 0)),
                  p_neg = sum(weight_prop[weight_num < 0]),
                  p_pos = sum(weight_prop[weight_num > 0])),
             by = c("sim_type", "replicate", 
                    "regrowth", "weight_id", "gen")]
    
    
    df <- na.omit(df)

    df[, p_pos_var := n_pos / (n_pos + n_neg)]
    df[, n_morphs := n_pos + n_neg]
    # plot
    ggplot(df, 
           aes(group = replicate))+
      geom_ribbon(
        aes(x = gen, 
            ymin = 1 - p_neg,
            ymax = (1 - p_neg) + (n_pos/50)),
        fill = "steelblue",
        alpha = 0.3
      )+
      geom_ribbon(
        aes(x = gen, 
            ymin = 1 - p_neg,
            ymax = (1 - p_neg) - (n_neg/50)),
        fill = "red",
        alpha = 0.3
      )+
      geom_line(aes(gen, 1 - p_neg),
                lwd = 0.2)+
      facet_grid(~ weight_id,
                 labeller = labeller(weight_id = label_wt))+
      coord_cartesian(ylim = c(-0.5, 1.5))+
      scale_y_continuous(breaks = c(0, 1),
                         labels = c("0", "1"))+
      ggthemes::theme_tufte(base_family = "sans",
                            base_size = 6)+
      theme(axis.text.x = element_blank(),
            panel.background = element_rect(
              fill = "grey95",
              colour = NA
            ),
            panel.grid = element_blank())+
      labs(x = "generation",
           y = "p(+ve weight)",
           title = title)
  })
  
  figure <- patchwork::wrap_plots(subfigures, ncol = 1)
  
  # figure filename
  fig_name <- unique(le[[1]]$sim_type)
  filename = sprintf("figures/fig_node_weight_summary_%s.png",
                     fig_name)
  message(fig_name)
  ggsave(figure,
         filename = filename,
         height = 10,
         width = 6,
         units = "in")
  
  return(figure)
  
}, data2)


```

## Summarise evolved movement weights

```{r}
# summarise the final generation
# read back in
data <- fread("data/results/data_weight_evolution.csv")

# handle weight value ranges and use UPPER bound
data[, weight_num := 
       stringi::stri_extract_last(weight_value, 
                                  regex = "[-0-9]+\\.\\d{2}")]
# assign numeric
data[, weight_num := as.numeric(weight_num)]
```

```{r}
# get max gen
data <- data[gen > 900, ]

weight_summary <- data[weight_prop >= 0.001, 
                       list(p_pos = sum(weight_prop[weight_num > 0]),
                            n_pos = length(unique(weight_num[weight_num > 0])),
                            n_neg = length(unique(weight_num[weight_num < 0]))),
                       by = c("sim_type", "replicate", "regrowth", "weight_id",
                              "gen")]
```

### Prepare figure

```{r}
label_wt <- c(
  # sprintf("weight: %s", c(2:8, 99))
  c("m(non-h)", "m(hand)", "m(food)",
    "f(bias)", "f(non-h)", "f(hand)", "f(food)", 
    "m(indivs)", "f(total)")
)
names(label_wt) <- c(seq(2, 8), 51, 99)

# remove random
weight_summary_move <- weight_summary[sim_type != "random" &
                                   weight_id %in% c(2:4, 51)]

# arrange order
weight_summary_move[, sim_type := factor(sim_type,
                                    levels = c("foragers",
                                               "obligate",
                                               "facultative"))]
```

```{r plot_prop_pos}
# split for labels
weight_summary_move <- split(weight_summary_move, by = "weight_id")

# arrange order
weight_summary_move <- weight_summary_move[as.character(c(4, 3, 2, 51))]

# make plot
subplots_wt_move <- Map(f = function(df) {
  ggplot(df)+
  geom_smooth(aes(regrowth, p_pos,
                group = interaction(sim_type),
                colour = sim_type),
             lwd = 0.5, alpha = 0.5,
             position = position_dodge(width = 0.01))+
  geom_point(aes(regrowth, p_pos,
                group = interaction(replicate, sim_type, gen),
                colour = sim_type,
                shape = sim_type),
              # size = 2,
              alpha = 0.5,
              fill = NA,
             position = position_dodge(width = 0.01))+
  scale_colour_manual(
    values = qualitative_hcl(3, "Set2", l = 20, rev = T)
  )+
  scale_x_sqrt(breaks = c(0.01, 0.1, 0.25))+
  scale_y_continuous(breaks = c(0, 0.5, 1))+
  scale_shape_manual(values = c(21, 22, 24))+
  coord_fixed(ratio = 0.5,
              xlim = c(0.001, 0.25),
              ylim = c(0, 1))+
  theme_test(base_size = 12)+
  theme(
    legend.position = "none",
    panel.background = element_rect(
      fill = "grey95"
    )
  )+
  labs(x = "growth rate",
       y = "p(+ve weight)")
}, weight_summary_move)
```

```{r}
# summarise the variation
weight_move_var <- Map(
  function(df) {
    df <- copy(df)
    df[, p_pos := NULL]
    df <- melt(df, id.vars = c("sim_type", "replicate", "regrowth", "weight_id", "gen"))
    df[, value := ifelse(variable == "n_neg", -value, value)]
  },
  weight_summary_move
)

pal <- c(rbind(
  qualitative_hcl(3, "Set2", l = 20, rev = T),
  qualitative_hcl(3, "Set2", l = 50, rev = T)
))

# select order
weight_move_var <- weight_move_var[as.character(c(4, 3, 2, 51))]

subplots_move_variation <- Map(function(df) {
  ggplot(df)+
  geom_hline(
    yintercept = 0,
    col = "grey",
  )+
  geom_col(aes(regrowth, value,
               fill = interaction(variable, sim_type),
               group = interaction(regrowth, replicate, gen)),
           width = 0.1,
           position = position_dodge(width = 0.01))+
  scale_x_sqrt(breaks = c(0.01, 0.1, 0.25))+
  scale_y_continuous(
    breaks = c(-10, 10),
    labels = c("-ve", "+ve")
  )+
  facet_grid(~sim_type,
             labeller = labeller(
               sim_type = c("foragers" = "Sc.1",
                            "obligate" = "Sc.2",
                            "facultative" = "Sc.3")
             ))+
  scale_fill_manual(
    values = pal
  )+
  theme_void(base_size = 12)+
  theme(
    axis.text.y = element_text(size = 8),
    axis.title.y = element_text(angle = 90),
    legend.position = "none",
    panel.background = element_rect(
      fill = "grey95"
    )
  )+
  labs(x = "growth rate",
       y = "# phenotypes")
}, weight_move_var)
```


```{r}
# merge plots
fig_move_weight_end <-
  wrap_plots(append(subplots_wt_move,
                    subplots_move_variation), 
             ncol = 4)+
  plot_annotation(tag_levels = "a",
                  tag_prefix = "(",
                  tag_suffix = ")") &
  theme(plot.tag = element_text(face = "bold",
                                size = 12))

# save
ggsave(fig_move_weight_end,
       filename = "figures/fig_03_move_weight_end_vals.png",
       height = 5, width = 10)
```


### Summarise evolved strategy weights

```{r}
label_wt <- c(
  # sprintf("weight: %s", c(2:8, 99))
  c("m(non-h)", "m(hand)", "m(food)",
    "f(bias)", "f(non-h)", "f(hand)", "f(food)", "f(total)")
)
names(label_wt) <- c(seq(2, 8), 99)

# remove random
weight_summary_strategy <- weight_summary[sim_type != "random" &
                                   weight_id %in% c(5:8, 99)]

# arrange order
weight_summary_strategy[, sim_type := factor(sim_type,
                                    levels = c("foragers",
                                               "obligate",
                                               "facultative"))]
# split for labels
weight_summary_strategy <- split(weight_summary_strategy, by = "weight_id")
# arrange
weight_summary_strategy <- weight_summary_strategy[as.character(
  c(5, 8, 7, 6, 99)
)]

# make plot
subplots_wt_strat <- Map(f = function(df) {
  ggplot(df)+
  geom_line(aes(regrowth, p_pos,
                group = interaction(replicate, sim_type),
                colour = sim_type),
             lwd = 0.2,
             position = position_dodge(width = 0.01))+
  geom_point(aes(regrowth, p_pos,
                group = interaction(replicate, sim_type),
                colour = sim_type,
                shape = sim_type),
              size = 2,
              # shape = 21,
              fill = NA,
             position = position_dodge(width = 0.01))+
  scale_colour_manual(
    values = qualitative_hcl(3, "Set2", l = 20, rev = T)
  )+
  scale_x_sqrt(breaks = c(0.01, 0.1, 0.25))+
  scale_y_continuous(breaks = c(0, 0.5, 1))+
  scale_shape_manual(values = c(21, 22, 24))+
  coord_fixed(ratio = 0.5,
              xlim = c(0.001, 0.25),
              ylim = c(0, 1))+
  theme_test(base_size = 12)+
  theme(
    legend.position = "none",
    panel.background = element_rect(
      fill = "grey95"
    )
  )+
  labs(x = "growth rate",
       y = "p(+ve weight)")
}, weight_summary_strategy)
```

```{r}
# summarise the variation
weight_strat_var <- Map(
  function(df) {
    df <- copy(df)
    df[, p_pos := NULL]
    df <- melt(df, id.vars = c("sim_type", "replicate", "regrowth", "weight_id"))
    df[, value := ifelse(variable == "n_neg", -value, value)]
  },
  weight_summary_strategy
)

subplots_strat_variation <- Map(function(df) {
  ggplot(df)+
  geom_hline(
    yintercept = 0,
    col = "grey",
  )+
  geom_col(aes(regrowth, value,
               fill = interaction(variable, sim_type),
               group = interaction(regrowth, replicate)),
           width = 0.1,
           position = position_dodge(width = 0.01))+
  scale_x_sqrt(breaks = c(0.01, 0.1, 0.25))+
  scale_y_continuous(
    breaks = c(-10, 10),
    labels = c("-ve", "+ve")
  )+
  facet_grid(~sim_type,
             labeller = labeller(
               sim_type = c("foragers" = "Sc.1",
                            "obligate" = "Sc.2",
                            "facultative" = "Sc.3")
             ))+
  scale_fill_manual(
    values = pal
  )+
  theme_void(base_size = 12)+
  theme(
    axis.text.y = element_text(size = 8),
    axis.title.y = element_text(angle = 90),
    legend.position = "none",
    panel.background = element_rect(
      fill = "grey95"
    )
  )+
  labs(x = "growth rate",
       y = "# phenotypes")
}, weight_strat_var)
```

```{r}
# make patchwork
fig_strategy_weight_end <-
  wrap_plots(append(subplots_wt_strat,
                    subplots_strat_variation),
             ncol = 5)+
  patchwork::plot_annotation(tag_levels = "a", 
                             tag_prefix = "(",
                             tag_suffix = ")") &
  theme(plot.tag = element_text(face = "bold"))

# save
ggsave(fig_strategy_weight_end,
       filename = "figures/fig_04_strategy_weight_end_vals.png",
       dpi = 300,
       height = 4, width = 12)
```

