--- 
knit: "bookdown::render_book"
title: "Supplementary Material for _The Joint Evolution of Movement and Competition Strategies_"
author:
    - Pratik R. Gupte
    - Christoph F.G. Netz
    - Franz J. Weissing
date: "`r Sys.Date()`"
output: bookdown::pdf_document2
documentclass: scrreprt
toc-depth: 1
secnumdepth: 2
geometry: "left=3cm, right=3cm, top=2.5cm, bottom=2.5cm"
link-citations: yes
github-repo: pratikunterwegs/kleptomove-ms
description: "Supplementary Material for _The Joint Evolution of Movement and Competition Strategies_"
---

In this Supplementary Material, we show two separate kinds of figures.

In Section 1, **Landscape Depletion across $r_{max}$**, we show the development of the prey-item landscape across different regrowth rates that we explored for our model. A summary of the eco-evolutionary dynamics for each $r_{max}$, in each scenario, can be found in the main text (see Main Text Figure 6).

In Section 2, **Evolution of Decision Making Weights**, we show the frequency of the movement decision making weights across generations, for an $r_{max}$ of 0.01 (the default value, with results presented in the main text). In addition, for scenario 3, we show the evolution of the strategy weight with respect to handlers, i.e., the foraging strategy response of individuals to the presence of handlers.
