---
output:
  pdf_document: default
editor_options:
  chunk_output_type: console
---

# Landscape Depletion across $r_{max}$

```{r}
# load libraries
library(data.table)
library(ggplot2)
library(patchwork)
```

## Load data

```{r}
# split by simulation and regrowth
data = fread("../data_sim/results/data_landscape_item_count_1_50.csv")
data = data[regrowth %in% c(0.001, 0.005, 0.02, 0.05),]

data = split(data, by = c("sim_type"))

data = lapply(data, function(df) {
  split(df, by = "regrowth")
})
```

## Plot landscape item counts

### Temporary function

```{r}
plot_subplots = function(df) {
  ggplot(df)+
  geom_tile(
    aes(x, y,
        fill = items)
  )+
  scale_fill_distiller(
    palette = "Blues", 
    direction = 1,
    limits = c(1, 5),
    na.value = "white"
  )+
  facet_grid(~ gen,
             labeller = label_both)+
  coord_equal(expand = F) +
  kleptomoveMS::theme_custom(landscape = T) +
  theme(legend.position = "right",
        legend.key.width = unit(1, units = "mm"),
        legend.key.height = unit(5, units = "mm"),
        # legend.text = element_text(size = 6),
        # legend.title = element_text(size = 6)
  ) +
  labs(fill = "# Prey", size = "# Indiv.",
       title = sprintf("regrowth: %s", unique(df$regrowth)))
}
```


```{r}
# wrap all plots
plots = lapply(data, function(l) {
  subplots = lapply(l, plot_subplots)
  wrap_plots(subplots, ncol = 2) &
  plot_annotation(
    tag_levels = "A"
  ) &
  theme(
    plot.tag = element_text(face = "bold")
  ) 
})

# save plots
# invisible(
#   lapply(c("foragers", "obligate", "facultative", "random"), function(p) {
#     ggsave(
#       plots[[p]],
#       filename = sprintf("supplementary_material/figures/fig_landscape_rmax_%s.png",
#                          p)
#     )
#   })
# )
```

```{r, fig.cap="In scenario 1, foragers completely deplete the resource landscape within 10 generations at low $r_{max}$ (**A, B**). However, at $r_{max}$ > 0.01 (**C, D**), prey item regeneration exceeds depletion and the resource landscape is rapidly saturated until most cells carry 5 items, the maximum allowed in our model."}
plots[["foragers"]]
```

```{r, fig.cap="In scenario 2, foragers can only deplete the resource landscape at very low $r_{max}$ (**A**): 1 prey item generated per 1,000 timesteps, or 2.5 generations. At all $r_{max} \geq$ 0.05 (**B, C, D**), prey item regeneration matches or exceeds depletion and the resource landscape either shows strong spatial structure, or is entirely saturated with prey items."}
plots[["obligate"]]
```

```{r, fig.cap="Scenario 3 is similar to scenario 1 at low $r_{max}$ (**A, B**), where foragers completely deplete the resource landscape). Similarly, at $r_{max} >$ 0.01 (**C, D**), prey item regeneration exceeds depletion and the resource landscape is rapidly saturated to a carrying capacity of 5 prey items per cell."}
plots[["facultative"]]
```