---
output:
 pdf_document: default
editor_options:
 chunk_output_type: console
---

# The effect of local dispersal

Up until now we have only considered global dispersal, where offspring are homogeneously distributed over the entire landscape. If offspring dispersal is more local, the spatial population dynamics may become more intricate, and kin competition or local adaptation may become influential. We therefore ran the simulations presented in the main text also under local dispersal (dispersal radius = 2). 

In summary, scenarios 1 and 3 yield similar results under local as under global dispersal, while scenario 2 shows some interesting dynamics typical of reaction-diffusion systems. In scenario 1, the resource landscape plots A, the activity budget and intake plots B and C, as well as the evolved movement strategies E exactly match the simulation results shown in Figure 1 of the main text. Solely the correlations between number of foragers and cell productivity are higher under local dispersal than under global dispersal (panel D). This is a straight-forward consequence of local dispersal, where individuals occurring on more productive cells have a higher intake rate and therefore produce more offspring than individuals on less productive cells. Thus, under local dispersal many agents already start out on more productive cells. This does not seem to impact movement strategies. 

The same is true for scenario 3: After the initial depletion of the landscape, kleptoparasitic behavior spreads, and the landscape is somewhat replenished again. Also here, the landscape snapshots, the activity budget, as well as the intake plot and the evolved movement strategies match the global dispersal case. The difference in competition strategy (panel F) corresponds to the observed bistability (compare _Main Text_ Fig. 6). Again, the correlation between number of foragers and cell productivity is higher under local dispersal than under global dispersal, in the latter averaging in late generations around 0.1, and in the former around 0.2.

Scenario 2 is the only one where we observed a marked difference between local and global dispersal. As soon as kleptoparasites occur, they spread and become locally abundant, driving foragers to local extinction. The kleptoparasites themselves then wither away due to a lack of foragers to steal from, after which foragers may colonize the area once again. This spatial instability repeats itself over wide parts of the landscape, driven by the extinction, recolonization and diffusion of foragers and kleptoparasites. Kleptoparasites and foragers here effectively form a reaction-diffusion system, as observed in a number of studies, including our work on predator-prey interactions as well [@netz2021]. Snapshots of this dynamic pattern can be seen in Fig. S14A. As a consequence, the proportions of kleptoparasites and foragers, as well as the total per capita intake of the population fluctuate widely (panels B and C). The correlations between individual densities and cell quality lie around zero and are therefore not much different from the results observed under global dispersal (_Main Text_ Fig. 2D). An interesting difference to global dispersal is to be found in the movement strategies. While kleptoparasites have similar preferences under global and local dispersal, foragers have much stronger item preferences under local dispersal. Due to the pattern of extinction and recolonization under local dispersal, there are parts of the landscape not only rich in food items, but also free from kleptoparasites, and thus a strong preference for items becomes beneficial.

![**The effect of local dispersal in scenario 1**. **(A)** Foragers swiftly deplete the resource landscape and maintain item scarcity throughout the rest of the simulation, just like under global dispersal. Items and agents are homogeneously distributed. The population quickly reaches an equilibrium in its **(B)** activity budget and **(C)** mean per-capita intake, that is identical to global dispersal. **(D)** The number of foragers per cell is more positively correlated with cell productivity under local than under global dispersal. **(E)** The same wide range of movement strategies observed under global dispersal exists under local dispersal as well.](figures/fig_local_dispersal_sc_01.png)

![**The effect of local dispersal in scenario 2**. **(A)** Foragers initially deplete prey items, but with the rise of kleptoparasistism, the resource landscape becomes very heterogeneous, with some areas densely populated and scarce in prey items, and others without consumers and fully stocked with items.This pattern is produced by the local dynamics of kleptoparasites and foragers: Kleptoparasites become more common where foragers are common, until the latter go locally extinct. Thereupon also the kleptoparasites vanish, and prey items replenish until foragers are reintroduced via diffusion. **(B)** Proportions of kleptoparasitses and foragers, as well as **(C)** mean per-capita intake fluctuate greatly. **(D)** Cell quality and number of individuals are uncorrelated as the spatial dynamics between kleptoparasites and foragers dominate over any interaction between cell quality and number of individuals. **(E)** Kleptoparasites evolve the same preferences under local dispersal as under global dispersal, but foragers have a much stronger preference for prey-items, caused by the abundance of deserted, fully-stocked parts of the landscape.](figures/fig_local_dispersal_sc_02.png)

![**The effect of local dispersal in scenario 3**. **(A)** Individuals swiftly deplete the resource landscape, but prey abundances recover with the rise of kleptoparasitism, as is observed under global dispersal. Items and agents are homogeneously distributed. **(B)** By generation 30, the proportion of time spent searching (blue line), handling (green line), and stealing prey (red line) reach values in the range of the ones observed under global dispersal. **(C)** The mean per-capita intake drops after the initial peak, and then recovers slightly, identically to global dispersal. **(D)** The number of foragers per cell is more positively correlated with cell productivity under local than under global dispersal. **(E)** Movement strategies concentrate around a strong preference for handlers, and **(F)** individuals tend to steal even when there are no handlers and less than 3 prey items available. This falls into the range of variation observed between replicates under global dispersal.](figures/fig_local_dispersal_sc_03.png)

\newpage
