---
output: html_document
editor_options:
  chunk_output_type: console
---

# Prepare Activity Budget Plots

Load libraries.

```{r }
library(data.table)

library(ggplot2)
library(patchwork)
library(colorspace)
```

## Get data

```{r }
# activity data
data_activity <- fread("data_sim/results/data_strategy_gen.csv")
data_activity <- data_activity[
  # sim_type == "foragers" &
    regrowth == 0.01
    # variable != "stealing"
]

# remove stealing from foragers
data_activity = data_activity[!(sim_type == "foragers" & variable == "stealing")]
```

Split by simulation type.

```{r}
data_activity = split(
  data_activity, by = "sim_type"
)
```

## Activity budget plot

```{r }
# fig_activity <-
plot_activity = lapply(data_activity, function(df) {
  
  # colours and labels
  col_vals = c(
    foraging = "dodgerblue4",
    handling = "forestgreen",
    stealing = "indianred"
  )
  label_vals = c(
    foraging = "Searching for prey",
    handling = "Handling prey",
    stealing = "Attempting to steal"
  )
  if(unique(df$sim_type) == "foragers") {
    col_vals = col_vals[names(col_vals) != "stealing"]
    label_vals = label_vals[names(label_vals) != "stealing"]
  }
  
  ggplot(df) +
  
  geom_line(
    aes(
      gen, value,
      colour = variable,
      group = interaction(variable, replicate)
    )
  ) +
  scale_colour_manual(
    values = col_vals,
    labels = label_vals
    # breaks = c("foraging", "handling", "stealing")
  ) +
  scale_y_continuous(
    labels = scales::percent,
    breaks = seq(0, 1, 0.25)
  ) +
  scale_x_log10(
    breaks = c(1, 3, 10, 30, 100, 300, 1000)
  ) +
  coord_cartesian(
    xlim = c(1, 1000),
    ylim = c(0, 1),
    expand = T
  ) +
  theme_test(
    base_size = 8,
    base_family = "Arial"
  ) +
  theme(
    legend.position = "top",
    legend.key.height = unit(2, units = "mm"),
    axis.text.y = element_text(
      angle = 90, hjust = 0.5
    )
  ) +
  labs(
    x = "Generation",
    y = "% Time",
    colour = NULL
  )+
  guides(colour = guide_legend(nrow = 1))
})

plot_activity = plot_activity[c(
  "foragers", "obligate", "facultative", "random"
)]


# save as R object
save(plot_activity, file = "figures/plot_activity.Rds")
```


## Mean per capita intake plot


```{r }
plot_intake <- lapply(data_activity, function(df) {
  ggplot(
    unique(df,
      by = c("gen", "replicate", "pop_fitness")
    )
  ) +
  geom_path(
    aes(gen, pop_fitness,
      group = replicate
    ),
  ) +
  scale_x_log10(
    breaks = c(1, 3, 10, 30, 100, 300, 1000)
  ) +
  coord_cartesian(
    # xlim = c(1, 50),
    xlim = c(1, 1000),
    ylim = c(0, 50),
    expand = T
  ) +
  theme_test(
    base_size = 8, 
    base_family = "Arial"
  ) +
  labs(
    x = "Generation",
    y = "Mean per capita intake"
  )
})

plot_intake = plot_intake[c(
  "foragers", "obligate", "facultative", "random"
)]

# save
save(plot_intake, file = "figures/plot_intake.Rds")
```

## Correlation with quality

```{r }
# raw correlation data
data_quality <- fread("data_sim/results/data_quality_matching_rule.csv")
data_quality <- data_quality[regrowth == 0.01, ]
```

```{r}
data_quality = split(data_quality, by = "sim_type")
```

```{r}
plots_quality = lapply(data_quality, function(df) {

  # colour values
  col_vals = c(
    "all_agents" = "navy",
    "foragers" = "royalblue",
    "klepts" = "indianred"
  )
  shape_vals = c(
    "all_agents" = 1,
    "foragers" = 0,
    "klepts" = 2
  )
  label_vals = c(
    "foragers" = "Foragers",
    "klepts" = "Klept."
  )
  if(unique(df$sim_type) == "obligate") {
    col_vals = col_vals[names(col_vals) != "all_agents"]
    shape_vals = shape_vals[names(shape_vals) != "all_agents"]
  }

  ggplot(df) +
  geom_hline(
    yintercept = 0,
    lty = 2,
    size = 0.2
  ) +
  geom_point(
    data = df,
    aes(
      x = gen,
      y = cf,
      colour = strategy,
      shape = strategy
    ),
    stroke = 0.5,
    show.legend = length(unique(df$strategy)) > 1
  ) +
  scale_colour_manual(
    values = col_vals,
    labels = label_vals
  )+
  scale_shape_manual(
    values = shape_vals,
    labels = label_vals
  )+
  theme_test(
    base_size = 8,
    base_family = "Arial"
  ) +
  coord_cartesian(
    ylim = c(-0.5, 0.5),
    xlim = c(1, 1000),
    expand = T
  ) +
  xlim(0, 50) +
  labs(
    x = "Generation",
    y = "Corr. # indivs. ~ cell quality",
    colour = NULL,
    shape = NULL
  )
})

plots_quality = plots_quality[c(
  "foragers", "obligate", "facultative", "random"
)]

# save
save(plots_quality, file = "figures/plot_quality.Rds")
```


## Plot landscape and agent distributions


```{r }
# get landscape and agent data
data_land <- fread("data_sim/results/data_landscape_progression.csv")
data_land <- data_land[gen %in% c(1, 10, 50, 950) & regrowth == 0.01, ]

data_agent = fread("data_sim/results/data_agent_locations.csv")
data_agent <- data_agent[gen %in% c(1, 10, 50, 950) & regrowth == 0.01, ]
```

```{r}
data_land = split(data_land, by = "sim_type")
data_agent = split(data_agent, by = "sim_type")
```

```{r}
plots_landscape = 
Map(data_land, data_agent, f = function(df_land, df_agent) {
  ggplot() +
  geom_tile(
    data = df_land,
    aes(x, y, fill = items),
    alpha = 0.5
  ) +
  geom_point(
    data = df_agent[agents > 0, ],
    aes(x, y, colour = agents),
    shape = 4,
    size = 0.5,
    stroke = 0.5
  ) +
  facet_grid(
    ~gen,
    labeller = label_both
  ) +
  scale_fill_continuous_sequential(
    palette = "Batlow",
    l1 = 20, l2 = 100,
    begin = 0.2,
    limits = c(1, NA),
    na.value = "white",
    name = "# Prey",
    rev = T,
    guide = guide_legend(order = 1)
  )+
  scale_colour_continuous_sequential(
    palette = "Grays",
    begin = 0.5,
    na.value = "black",
    limits = c(1, 5),
    name = "# Consumers",
    guide = guide_legend(order = 2)
  )+
  coord_equal(expand = F) +
  kleptomoveMS::theme_custom(
    landscape = T, 
    base_size = 8,
    base_family = "Arial"
  ) +
  theme(legend.position = "bottom")
})

plots_landscape = plots_landscape[c(
  "foragers", "obligate", "facultative", "random"
)]

save(
  plots_landscape,
  file = "figures/plots_landscape.Rds"
)
```

## Make scenario specific figures

```{r}
figs_1_2_4 = Map(
  plots_landscape, plot_activity, plot_intake, plots_quality,
  f = function(p1, p2, p3, p4) {
    p5 = wrap_plots(
      p2, p3, p4,
      design = "ABC"
    ) +
    plot_layout(guides = "collect") &
    theme(
      legend.position = "bottom"
    )

    wrap_plots(
      p1,
      p5,
      ncol = 1
    ) +
    plot_annotation(
      tag_levels = "A"
    ) &
    theme(
      plot.tag = element_text(
        face = "bold",
        size = 10
      )
    )
  }
)

# check names
names(figs_1_2_4)

# save figures
invisible(
  Map(figs_1_2_4, c(as.character(c(1,2,4)), "random"), f = function(p, n) {
    ggsave(
      p,
      filename = sprintf("figures/fig_0%s.png", n),
      height = 110, width = 150, units = "mm"
    )
  })
)
```