---
output: html_document
editor_options:
  chunk_output_type: console
---

# Prepare Activity Budget Plots

Load libraries.

```{r }
library(data.table)

library(ggplot2)
library(patchwork)
library(colorspace)
```

## Get data

```{r }
# activity data
data_activity <- fread("data_sim/results/data_strategy_gen.csv")
data_activity <- data_activity[
  # sim_type == "foragers" &
    regrowth == 0.01
    # variable != "stealing"
]

# remove stealing from foragers
data_activity = data_activity[!(sim_type == "foragers" & variable == "stealing")]
```

Split by simulation type.

```{r}
data_activity = split(
  data_activity, by = "sim_type"
)
```

## Activity budget plot

```{r }
# fig_activity <-
plot_activity = lapply(data_activity, function(df) {
  
  # colours and labels
  col_vals = c(
    foraging = "dodgerblue4",
    handling = "forestgreen",
    stealing = "indianred"
  )
  label_vals = c(
    foraging = "Searching for prey",
    handling = "Handling prey",
    stealing = "Attempting to steal"
  )
  if(unique(df$sim_type) == "foragers") {
    col_vals = col_vals[names(col_vals) != "stealing"]
    label_vals = label_vals[names(label_vals) != "stealing"]
  }
  
  ggplot(df) +
  
  geom_line(
    aes(
      gen, value,
      colour = variable,
      group = interaction(variable, replicate)
    )
  ) +
  scale_colour_manual(
    values = col_vals,
    labels = label_vals
    # breaks = c("foraging", "handling", "stealing")
  ) +
  scale_y_continuous(
    labels = scales::percent,
    breaks = seq(0, 1, 0.25)
  ) +
  scale_x_log10(
    breaks = c(1, 3, 10, 30, 100, 300, 1000)
  ) +
  coord_cartesian(
    # xlim = c(1, 50),
    ylim = c(0, 1),
    expand = F
  ) +
  theme_test(base_size = 12) +
  theme(
    legend.position = "top",
    legend.key.height = unit(2, units = "mm"),
    axis.text.y = element_text(
      angle = 90, hjust = 0.5
    )
  ) +
  labs(
    x = "Generation",
    y = "% Time",
    colour = NULL
  )+
  guides(colour = guide_legend(nrow = 2, ncol = 2, byrow = T))
})

# wrap figures to check
wrap_plots(plot_activity)

# save as R object
save(plot_activity, file = "figures/plot_activity.Rds")
```


## Mean per capita intake plot


```{r }
plot_intake <- lapply(data_activity, function(df) {
  ggplot(
    unique(df,
      by = c("gen", "replicate", "pop_fitness")
    )
  ) +
  geom_path(
    aes(gen, pop_fitness,
      group = replicate
    ),
  ) +
  scale_x_log10(
    breaks = c(1, 3, 10, 30, 100, 300, 1000)
  ) +
  coord_cartesian(
    # xlim = c(1, 50),
    ylim = c(0, 50),
    expand = F
  ) +
  theme_test(base_size = 12) +
  labs(
    x = "Generation",
    y = "Mean per capita intake"
  )
})

# wrap to check
wrap_plots(plot_intake)

# save
save(plot_intake, file = "figures/plot_intake.Rds")
```

## Correlation with quality

```{r }
# raw correlation data
data_quality <- fread("data_sim/results/data_quality_matching_rule.csv")
data_quality <- data_quality[regrowth == 0.01, ]
```

```{r}
data_quality = split(data_quality, by = "sim_type")
```

```{r}
plots_quality = lapply(data_quality, function(df) {
  ggplot(df) +
  geom_hline(
    yintercept = 0,
    lty = 2,
    size = 0.2
  ) +
  geom_point(
    data = df,
    aes(
      x = gen,
      y = cf,
      colour = strategy,
      shape = strategy
    ),
    stroke = 0.5,
    show.legend = F
  ) +
  scale_colour_manual(
    values = c(
      "all_agents" = "navy",
      "foragers" = "royalblue",
      "klepts" = "indianred"
    )
  )+
  scale_shape_manual(
    values = c(
      "all_agents" = 1,
      "foragers" = 0,
      "klepts" = 2
    )
  )+
  theme_test(
    base_size = 12
  ) +
  coord_cartesian(
    ylim = c(-0.5, 0.5),
    xlim = c(0, 50),
    expand = F
  ) +
  xlim(0, 50) +
  labs(
    x = "Generation",
    y = "Corr. # indivs. ~ cell quality"
  )
})

# check plots
wrap_plots(plots_quality)

# save
save(plots_quality, file = "figures/plot_quality.Rds")
```


## Plot landscape and agent distributions


```{r }
# get landscape and agent data
data_land <- fread("data_sim/results/data_layer_counts_1_150.csv")
data_land <- data_land[gen %in% c(1, 10, 50) &regrowth == 0.01, ]
```

```{r}
data_land = split(data_land, by = "sim_type")
```

```{r}
lapply(data_land, function(df) {
  ggplot(df) +
  geom_tile(
    aes(x, y, fill = items)
  ) +
  # geom_point(
  #   data = df[agents > 0, ],
  #   aes(x, y, colour = agents),
  #   shape = 4,
  #   size = 0.5,
  #   stroke = 1,
  #   alpha = 0.8
  # ) +
  facet_grid(
    ~gen,
    labeller = label_both
  ) +
  # scale_fill_continuous_sequential(
  #   palette = "Blues",
  #   begin = 0.1,
  #   limits = c(1, NA),
  #   na.value = "white",
  #   name = "# Prey",
  #   guide = guide_legend(order = 1)
  # )+
  scale_colour_continuous_sequential(
    palette = "Reds",
    begin = 0.2,
    # na.value = "darkred",
    # limits = c(1, 5),
    name = "# Consumers",
    guide = guide_legend(order = 2)
  )+
  coord_equal(expand = F) +
  kleptomoveMS::theme_custom(
    landscape = T, base_size = 12
  ) +
  theme(legend.position = "bottom")
}) |> 
  wrap_plots()
```

## WIP

## Figure 1 Foragers model

wrap figures together


```{r }
figure_1 <-
  wrap_plots(
    fig_activity, fig_intake,
    fig_matching_quality
  ) +
  plot_layout(guides = "collect") &
  theme(
    legend.position = "bottom"
  )

figure_1 =
  wrap_plots(
    fig_land_foragers,
    figure_1,
    ncol = 1
  ) +
  plot_annotation(
    tag_levels = "A"
  ) &
  theme(
    plot.tag = element_text(
      face = "bold",
      size = 12
    )
  )
```


save figure


```{r }
ggsave(figure_1,
  filename = "figures/fig_01.png",
  height = 120, width = 150, units = "mm"
)
```

