---
output: html_document
editor_options:
  chunk_output_type: console
---

# Get relative preferences

These are the relative preferences that determine movement strategies.

```{r }
# load libs
library(data.table)
library(stringr)
devtools::load_all()
```

Prepare data paths.

```{r}
# read paths
paths <- list.dirs("data_sim/", recursive = F)
paths <- paths[grep("rep_", paths)]

# make df
data = CJ(
  path = paths
)

# get replicate
data[, rep := as.numeric(
  stringr::str_extract_all(path, "rep_(\\d{3})") |> 
    stringr::str_extract_all("\\d{3}")
)]

# get sim type
data[, sim_type := stringr::str_extract(
  path, "obligate|facultative|foragers|random"
 ) 
]

data[, regrowth := as.numeric(str_extract(path, "(0\\.\\d+)"))]

# filter for focus regrowth
data = data[regrowth == 0.01,]
```

## Relative preference for movement cues

Read scaled movement weights from 2500 individuals in each simulation from generations 1, 10, 30, 100, and 950.

```{r}
data_rel_pref = copy(data)
data_rel_pref[, rel_pref := lapply(
  path, get_scaled_move_prefs, 
  gens = c(1, 10, 30, 100, 300, 950), n_agents = 2500
)]

data_rel_pref = data_rel_pref[, unlist(rel_pref, recursive = F),
  by = list(sim_type, rep, regrowth)
]

# assign strategy
data_rel_pref[, strategy := fcase(
  sim_type == "obliagte" & wt_5 > 0, "forager", 
  sim_type == "obliagte" & wt_5 > 0, "klept",
  sim_type != "obligate", "consumer"
  )
]

fwrite(data_rel_pref, file = "data/results/data_rel_pref.csv")
```

## Evolution of handler tracking

```{r}
# weight data
syndrome_data <- lapply(data$path, function(path) {
  kleptomoveMS::get_pref_handler_by_strat(
    data_folder = path,
    generations = unique(
      seq(1, 999, 2)
    ),
    weight_klept_bias = 5,
    weight_of_interest = c(
      handler_pref = 3
    ),
    handler_pref_by_strategy = TRUE
  )
})

# add to data
data_si_strategy <- copy(data)
data_si_strategy$syndrome_data <- syndrome_data
# unlist
data_si_strategy <- data_si_strategy[, unlist(syndrome_data, recursive = FALSE),
  by = c("sim_type", "rep", "regrowth")
]
# save data
fwrite(data_si_strategy, file = "data_sim/results/data_syndrome_by_strategy.csv")
```