---
output: html_document
editor_options:
  chunk_output_type: console
---

# Process landscape snapshots to get item and agent abundance

```{r }
library(data.table)
library(glue)
library(ggplot2)
```

## Get agent abundances

Prepare paths.

```{r}
# read paths
paths <- list.dirs("data_sim/", recursive = F)
paths <- paths[grep("rep_", paths)]

# select gens
gens_for_figure <- stringr::str_pad(
  unique(
    c(
      seq(1, 10),
      seq(10, 50, 10),
      seq(50, 950, by = 50)
    )
  ), 
  width = 5, pad = "0"
)

# make df
data = CJ(
  path = paths,
  gen = gens_for_figure
)

# get replicate
data[, rep := as.numeric(
  stringr::str_extract_all(path, "rep_(\\d{3})") |> 
    stringr::str_extract_all("\\d{3}")
)]

# get sim type
data[, sim_type := stringr::str_extract(
  path, "obligate|facultative|foragers|random"
 ) 
]

data[, regrowth := as.numeric(str_extract(path, "(0\\.\\d+)"))]

# get paths
data$image <- glue_data(data, "{path}/{gen}.png")
```

Prepare paths for scenario 2, which has to be handled differently to count foragers and kleptoparasites separately.

```{r }
# separate data for scenario 2
data_sc2 = data[sim_type == "obligate", ]

# separate other data
data = data[!data_sc2, on = names(data)]

# handle data from scenario 2
sc2_strat = data.table(strategy = c("foragers", "klepts"))
data_sc2 = setkey(data_sc2[, c(k = 1, .SD)], k)[
  sc2_strat[, c(k = 1, .SD)], allow.cartesian = TRUE]
data_sc2[, k := NULL]
```

## Process agent counts for all scenarios

```{r }
# get data for scenarios 1 and 3
agent_data <- lapply(data$image,
  kleptomoveMS::read_landscape,
  layer = c(1, 3), # read only foragers and klepts if any
  crop_dim = 60,
  type = "items"
)

# scenario 2 agent data
agent_data_sc2 = Map(function(file, strategy) {
  
  layer = ifelse(strategy == "foragers", 3, 1)
  
  d = kleptomoveMS::read_landscape(
    landscape_file = file, layer = layer,
    crop_dim = 60,
    type = "items"
  )
  
  d = d[items > 0, ]
  
  setnames(d, "items", strategy)
  
}, data_sc2$image, data_sc2$strategy)
```

## Remove unoccupied cells

```{r }
# remove where agents are 0
agent_data <- lapply(
  agent_data, function(df) {
    df <- df[items > 0, ]
    setnames(df, "items", "agents")
    # df[, agents := round(agents / 0.02)]
  }
)
```

## Process productivity layer

```{r }
quality_data <- kleptomoveMS::read_landscape(
  "data_sim/data_parameters/kernels32.png",
  layer = 1, crop_dim = 60, type = "items"
)

setnames(quality_data, old = "items", new = "quality")

# agent quality data
agent_data <- lapply(agent_data, function(df) {
  merge(
    df, quality_data, 
    by = intersect(names(df), names(quality_data)), 
    all = F
  )
})

# scenario 2 agent quality matching
agent_data_sc2 = lapply(agent_data_sc2, function(df) {
  merge(
    df, quality_data, 
    by = intersect(names(df), names(quality_data)), 
    all = F
  )
})
```

## Prepare data for export

```{r}
# unlist and merge with simulation parameters
data$layer_data <- agent_data

data_sc2$layer_data = agent_data_sc2

# remove cols
data = data[, !c("path", "image")]

# unlist
data <- data[, unlist(layer_data, recursive = F),
  by = c("sim_type", "gen", "rep", "regrowth")
]

# assign strategy
data$strategy =  "all_agents"

data_sc2 = data_sc2[, !c("path", "image")]
data_sc2 = data_sc2[, unlist(layer_data, recursive = F),
  by = c("sim_type", "gen", "rep", "regrowth",
         "strategy")
]
setnames(data_sc2, "foragers", "agents")

# bind rows together
data = rbindlist(list(data, data_sc2), use.names = TRUE)

# select data
data[, gen := as.numeric(gen)]
data <- data[, list(sim_type, gen, rep, regrowth, 
                    x, y, agents, quality, strategy)]

# save data
fwrite(data, file = "data_sim/results/data_input_matching.csv")
```

