kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_001_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_001_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_001_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_001_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_001_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_001_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_002_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_002_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_002_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_002_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_002_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_002_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_003_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_003_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_003_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_003_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_003_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_003_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_004_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_004_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_004_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_004_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_004_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_004_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_005_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_005_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_005_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_005_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_005_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_005_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_006_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_006_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_006_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_006_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_006_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_006_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_007_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_007_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_007_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_007_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_007_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_007_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_008_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_008_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_008_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_008_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_008_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_008_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_009_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_009_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_009_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_009_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_009_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_009_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_010_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_010_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=0 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_facultative_rep_010_gro_0.03
kleptomove config=../settings/config.ini landscape.item_growth=0.01 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_010_gro_0.01
kleptomove config=../settings/config.ini landscape.item_growth=0.02 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_010_gro_0.02
kleptomove config=../settings/config.ini landscape.item_growth=0.03 agents.forage=1 agents.obligate=0 agents.handling_time=5 agents.sprout_radius=2 outdir=../../data/sim_foragers_rep_010_gro_0.03
